CHANGELOG.md

Correct `camelcase` function name in the changelog.

Correct function name in changelog

---

lib/puppet/parser/functions/ensure_resource.rb

helps discovering duplication issues, especially when figthing boolean vs. string arguments

ensure_resource: be more verbose in debug mode

---

.fixtures.yml
.travis.yml
README.markdown
lib/puppet/functions/type_of.rb
lib/puppet/parser/functions/type.rb
lib/puppet/parser/functions/type3x.rb
spec/functions/type3x_spec.rb
spec/functions/type_spec.rb
spec/unit/puppet/functions/type_of_spec.rb

The `type()` function will cease to work on the new parser because 'type' is a reserved keyword. The `type3x()` function may be used to continue similar functionality, but will be deprecated in favor of the built-in typing system.
The `type_of()` function has been included to introspect types in the new parser.

(MODULES-1473) Deprecate type() function for new parser

---

spec/acceptance/fqdn_rotate_spec.rb

The existence of this directory is behavior for each test, but will also
stop rspec 3 from complaining.

Change all to each

---

Gemfile

The release of rspec 3.2.0 broke a lot of tests. rspec-puppet 2.0 has a dependency on rspec ~> 2.0, so pinning to that resolves the problems.  Additionally, the Gemfile didn't actually specify which version to use for Facter, even when there was an environment variable to that effect.

Fix Travis builds

---

lib/puppet/parser/functions/fqdn_rotate.rb
spec/functions/fqdn_rotate_spec.rb

[MODULES-1738](https://tickets.puppetlabs.com/browse/MODULES-1738) is similar to [Redmine-15791](http://projects.puppetlabs.com/issues/15791), which was addressed in puppetlabs/puppet@292233c. The current implementation of fqdn_rotate() leaves the global seed in a deterministic state, which is bad. Puppet::Util.deterministic_rand() exists to avoid running into this issue, but is only present starting in Puppet 3.2.0.
An alternative (and, IMO, superior) way to handle this would be to instead replace lines 34-37 of fqdn_rotate.rb with:
```ruby
Puppet::Parser::Functions.function('fqdn_rand')
function_fqdn_rand([elements, arguments]).to_i.times {
result.push result.shift
}
```
This would have the benefits of being much cleaner and not having duplicated code from the Puppet codebase that would …

(MODULES-1738) Don't modify the global seed in fqdn_rotate()

---

lib/puppet/parser/functions/is_domain_name.rb
spec/functions/is_domain_name_spec.rb

Fix is_domain_name() so it dup's its incoming argument
to avoid changing the original with a later chomp!

(MODULES-1771) Don't modify input to is_domain_name()

---

README.markdown
lib/puppet/parser/functions/ceiling.rb
spec/acceptance/ceiling_spec.rb
spec/functions/ceiling_spec.rb

This relates to https://tickets.puppetlabs.com/browse/MODULES-1735

Add a ceiling function to complement the floor function.

---

README.markdown

This documents the feature added in #56

Adding markdown for the range() function's 3rd argument

---

README.markdown
lib/puppet/parser/functions/validate_integer.rb
lib/puppet/parser/functions/validate_numeric.rb
spec/functions/validate_integer_spec.rb
spec/functions/validate_numeric_spec.rb

I saw MODULES-560 on Jira (https://tickets.puppetlabs.com/browse/MODULES-560) and had a need for it (check ports easily in a manifest), so I implemented it.
Added rspec unit tests, too.
Added necessary stuff to README.markdown, too.
Would be glad, if this gets merged... :) Thanks!

(MODULES-560) Add new functions validate_numeric() and validate_integer().

---

lib/puppet/parser/functions/dirname.rb
spec/functions/dirname_spec.rb

Added parameter type checking, a check for too many parameters, and tests for all.

Dirname typecheck

---

lib/puppet/parser/functions/is_domain_name.rb
spec/functions/is_domain_name_spec.rb

A valid host name can never have the dotted-decimal form #.#.#.#,
since at least the highest-level component label will be alphabetic.
See RFC 1123, Section 2.1
http://tools.ietf.org/html/rfc1123#section-2
Fixes PUP-3856

(MODULES-1670) Do not match dotted-quad IP address as domain name

---

README.markdown
lib/puppet/parser/functions/pw_hash.rb
spec/acceptance/pw_hash_spec.rb
spec/functions/pw_hash_spec.rb

As per [MODULES-1737](https://tickets.puppetlabs.com/browse/MODULES-1737), this PR provides a method of generating password hashes.  Tests coming.

(MODULES-1737) Add pw_hash() function

---

README.markdown
lib/puppet/parser/functions/fqdn_rand_string.rb
spec/acceptance/fqdn_rand_base64_spec.rb
spec/acceptance/fqdn_rand_string_spec.rb
spec/functions/fqdn_rand_string_spec.rb

As requested in [MODULES-1715](https://tickets.puppetlabs.com/browse/MODULES-1715), this PR provides `fqdn_rand_string()`, which generates random alphanumeric strings of the desired length.  It also provides `fqdn_rand_base64()`, which generates random base64 strings of the desired length.

(MODULES-1715) Add FQDN-based random string generator

---

spec/acceptance/fqdn_rand_base64_spec.rb
spec/acceptance/fqdn_rand_string_spec.rb

unsupported_platforms is not a valid identifier, and trying to use it
causes acceptance tests to error out before running any tests. The
correct identifier for the unsupported platforms constance is
UNSUPPORTED_PLATFORMS.

Fix unsupported platforms variable name in tests

---

lib/puppet/provider/file_line/ruby.rb
spec/unit/puppet/provider/file_line/ruby_spec.rb

This is a refactor of PRs: 
Closes https://github.com/puppetlabs/puppetlabs-stdlib/pull/427
Closes https://github.com/puppetlabs/puppetlabs-stdlib/pull/327
Closes https://github.com/puppetlabs/puppetlabs-stdlib/pull/317
Refactor eliminates the need to rewrite the file twice.

File_line checks provided after param if no match is found

---

spec/functions/validate_augeas_spec.rb

This fixes the test "Nicer Error Messages" in puppetlabs-stdlib/spec/functions/validate_augeas_spec.rb. Without it, 'rake spec' will always fail with RegexpError: empty char-class: /[]/ as Ruby tries and fails to build a pattern off the wrong entry in the inputs array.
I do not understand why I'm the only one to have run into this. But I believe this trivial fix is what the original author intended.

Fix off-by-one error in validate_augeas_spec.rb that was causing rspec failure

---

lib/puppet/parser/functions/loadyaml.rb
spec/functions/loadyaml_spec.rb

In ```loadyaml``` function, check if file exists before trying to import. If not exists, return nil.

Check if file exists before loading with loadyaml. If not, return nil

---

manifests/init.pp

previous behavior used class { 'stdlib::stages':} which isn't singleton and could cause duplication resource declaration on the stages class.
Since many community modules work by calling 'include stdlib' we should make stdlib's include of stages singleton as well.

uses include type class declaration

---

lib/puppet/parser/functions/pw_hash.rb

The previous change to this function broke it on JRuby before 1.7.17 by
attempting to use a variable that wasn't defined (`salt`). To fix this,
define `salt` ahead of time and use that instead of building the salt
later.
cf. https://github.com/puppetlabs/puppetlabs-stdlib/pull/443#discussion_r29718588

Fix pw_hash() on JRuby < 1.7.17

---

lib/puppet/parser/functions/range.rb

This restores functionality removed from `range()` by a recent commit, specifically the ability to make calls such as `range('2..3')`, `range('2...3')`, and `range('2-3')`.  Such removal should be done only on a new major version due to it being a breaking change and should be documented correctly.  I suspect this was done due to misreading of [one of the removed checks](https://github.com/puppetlabs/puppetlabs-stdlib/pull/443#discussion_r29721193), so I have also cleaned up the function a bit to clarify it. 
cf. https://github.com/puppetlabs/puppetlabs-stdlib/pull/443#commitcomment-11055565

Restore removed functionality to range()

---

spec/functions/type_of_spec.rb

The rspec-puppet matchers don't allow to check the return types, but
this is a pretty rare thing to need to do anyway, so probably not worth
patching rspec-puppet

Remove all the pops stuff

---

lib/facter/facter_dot_d.rb

b11311a moved the location of the facts.d cache but neglected to change the comment at the top of the file indicating its location. This rectifies that.

(FM-2130) Document new location of facts.d cache

---

lib/puppet/parser/functions/fqdn_rotate.rb

Without this, the global seed is reseeded on every use
of fqdn_rotate, which is a waste. Older rubies might even use a
time-base seed which adversly impacts the quality of the RNG.

fqdn_rotate: reset srand seed correctly on old ruby versions

---

lib/puppet/parser/functions/validate_integer.rb
lib/puppet/parser/functions/validate_numeric.rb
spec/functions/validate_integer_spec.rb
spec/functions/validate_numeric_spec.rb

Without this patch, Ruby 1.8's Hash#to_s behaviour causes [{1=>2}] to be
treated as "12" when validating values.

validate_integer, validate_numeric: explicitely reject hashes in arrays

---

README.markdown
lib/puppet/provider/file_line/ruby.rb
spec/unit/puppet/provider/file_line/ruby_spec.rb

Without this, `file_line` resource without the `match` parameter but with the `after` param will throw an error if there are multiple matches for the after expression. This patch creates the handling for the `multiple` parameter in handle_create_with_after. This allows you to add a line after the `after` expression if it appears at multiple points in a file without specifying the `match` param.
Updated reference to `file_line` in the README to reflect that the multiple parameter can be set when using `after` and/or `match` as the matching regex.

 (MODULES-2071) Patch file_line provider to use multiple with after

---

README.markdown
lib/puppet/parser/functions/fqdn_rotate.rb
spec/acceptance/fqdn_rotate_spec.rb
spec/functions/fqdn_rotate_spec.rb

Previously, the random number generator was seeded with the array or string to be rotated in addition to any values specifically provided for seeding. This behavior is potentially insecure in that it allows an attacker who can modify the source data to choose the post-shuffle order. While this is probably not a particularly big issue, it's still worth changing.
This also improves the documentation for `fqdn_rotate`.

fqdn_rotate: Don't use the value itself as part of the random seed

---

Gemfile

Only 2.2 contains all the features we're currently using. Documenting
that in the Gemfile should make that clear.

Gemfile: specify minimum rspec-puppet version

---

spec/acceptance/fqdn_rand_string_spec.rb
spec/acceptance/fqdn_rotate_spec.rb

This adds acceptance tests validating custom seed functionality in `fqdn_rotate()` and custom character set functionality in `fqdn_rand_string()`.
This depends on #462.

Improve fqdn_rotate/fqdn_rand_string acceptance tests

---

lib/puppet/parser/functions/time.rb
spec/functions/time_spec.rb

The time() function takes an argument of a timezone, and always returns
time in epoch format. The epoch format is the number of seconds that
have elapsed since January 1, 1970 (midnight UTC/GMT), not counting leap
seconds. This means that it is universally the same regardless of
timezones.
I don't know what the timezone argument is supposed to do, and it is not
documented. So lets just make 1.8.7 work like > 1.8.7

Fix time() on 1.8.7

---

lib/puppet/parser/functions/getvar.rb

Also eat the throw from the future parser when strict_variables is true.

Also catch :undefined_variable as thrown by future parser

---

metadata.json

Fairly self-explanatory.  This simply adds Solaris 12 to metadata.json.

Add support for Solaris 12

---

lib/puppet/parser/functions/has_interface_with.rb

facter (2.x) only provides facts without interface suffix for
* ipaddress
* netmask
'macaddress' and 'network' facts will always have the related interface
name appended. in turns lookupvar throws errors when strict_variables is
enabled.

catch and rescue from looking up non-existent facts

---

lib/puppet/parser/functions/upcase.rb

The documentation example shows an incorrect response when using the
function, this PR corrects the example to agree with what the function
actually does.

Fix documentation error in upcase

---

README.markdown
lib/puppet/provider/file_line/ruby.rb
lib/puppet/type/file_line.rb
spec/unit/puppet/provider/file_line/ruby_spec.rb
spec/unit/puppet/type/file_line_spec.rb

Adding tests and minor changes to make @WhatsARanjit's PR #451 work. 
The patch adds the optional `replace` attribute to file_line. It defaults to true, which maintains current behavior. Setting the attribute to false will allow users to ensure that a line matching the `match` attribute exists without overwriting it with the contents of `line` if the matching lines exists

[#puppethack] Adding replace attribute to file_line

---

README.markdown
lib/puppet/parser/functions/load_module_metadata.rb
spec/functions/load_module_metadata.rb

This function loads the metadata.json into a puppet variable. This enables a number of neat things such as:
* Which version of the module am I using? 2.x? 3.x?
* Which author of the module am I using? puppetlabs? example42?

Add load_metadata_json function

---

lib/puppet/provider/file_line/ruby.rb
lib/puppet/type/file_line.rb
spec/unit/puppet/provider/file_line/ruby_spec.rb
spec/unit/puppet/type/file_line_spec.rb

Puppet's boolean parameter type is only available in Puppet 3.3 and
higher, so change file_type's new "replace" parameter to a regular
parameter with true and false as possible values.  This matches the
existing "multiple" parameter.

(MODULES-2316) Change file_type boolean parameter to symbols

---

lib/puppet/provider/file_line/ruby.rb
lib/puppet/type/file_line.rb
spec/unit/puppet/provider/file_line/ruby_spec.rb

Split the `destroy` method of the file_type::ruby provider into two
private methods:  `handle_destroy_line` which is the same as the previous
`destroy` method, and `handle_destroy_with_match` which will destroy any
line which matches the `match` parameter, raising an error if multiple
lines match and the `multiple` parameter is not `true`.  This new
behavior is only used if the new boolean parameter `match_for_absence`
is `true` (it defaults to `false`).

[MODULES-2370] allow `match` parameter to influence `ensure => absent` behavior.

---

CHANGELOG.md
README.markdown
lib/puppet/parser/functions/dos2unix.rb
lib/puppet/parser/functions/unix2dos.rb
spec/functions/dos2unix_spec.rb
spec/functions/unix2dos_spec.rb

Add dos2unix and unix2dos functions to stdlib so that when using File resources with cross platform templates, the correct line endings can be enforced.
To show usage, here's an extract from README.md:
Returns the Unix version of the given string. Very useful when using a File resource with a cross-platform template.
~~~
file{$config_file:
ensure  => file,
content => dos2unix(template('my_module/settings.conf.erb')),
}
~~~
Returns the DOS version of the given string. Very useful when using a File resource with a cross-platform template.
~~~
file{$config_file:
ensure  => file,
content => unix2dos(template('my_module/settings.conf.erb')),
}
~~~

(MODULES-2410) Add new functions dos2unix and unix2dos

---

README.markdown
lib/puppet/parser/functions/union.rb
spec/acceptance/union_spec.rb
spec/functions/union_spec.rb

Add spec tests to test the new functionality:
*Case for 3 arrays.
*Case for 4 arrays.
Modify README to note new functionality.
This is for issue MODULE-2456, follow the precedent of MODULE-444.
This change allows union to be much more useful, unioning many arrays
in one line rather than in n lines. Additionally, as this is only added
functionality, and does not affect the 2 array case that all modules
currently using array are using, it should not affect any existing
modules utilizing union.
This is now useful, for example, for merging many arrays of resources
(eg: packages.) to generate just one list with no duplicates, to avoid
duplicate resource declarations.

(MODULES-2456) Modify union to accept more than two arrays

---

README.markdown

After commiting my changes yesterday, I noticed that union did not have a *Type*: xyz listed. 
I have checked through the readme and found that pw_hash also did not have this information. 
I also noticed that there was trailing whitespace on the prefix function.

Consistent Readme

---

README.markdown
lib/puppet/parser/functions/convert_base.rb
spec/functions/convert_base_spec.rb

Squashed, improved docs, updated error handling and unit tests by David S.

Adds a convert_base function, which can convert numbers between bases

---

lib/facter/root_home.rb
spec/fixtures/lsuser/root
spec/unit/facter/root_home_spec.rb

The root_home fact returns nil on AIX due to the operating system not providing getent. The recommended replacement for this is the 'lsuser' command.
This PR adds a new fact, confined to kernel=>aix to use libuser to return root's configured home directory.

Ticket/MODULES-2478 Make root_home fact work on AIX using native lsuser command

---

README.markdown
lib/puppet/parser/functions/try_get_value.rb
spec/acceptance/try_get_value_spec.rb
spec/functions/try_get_value_spec.rb

Extracts a value from a deeply-nested data structure
$data = {
'a' => {
'b' => [
'b1',
'b2',
'b3',
]
}
}
$value = fetch($data, 'a/b/2')
=> $value = 'b3'

Add a new function "try_get_value"

---

README.markdown
lib/puppet/parser/functions/str2bool.rb
spec/functions/str2bool_spec.rb

* previously the str2bool function did not accept 'TRUE' as a bool
type. This causes the function to now accept TRUE | FALSE strings
as a boolean type in order to be converted to a proper boolean.
* This would also cause Y, N, YES, NO to be accepted as boolean types
as well.

accept any case of boolean strings

---

README.markdown
lib/puppet/parser/functions/parsejson.rb
lib/puppet/parser/functions/parseyaml.rb
spec/acceptance/parsejson_spec.rb
spec/acceptance/parseyaml_spec.rb
spec/functions/parsejson_spec.rb
spec/functions/parseyaml_spec.rb

* Add default value support
Second argument will be returned if yaml cannot be parsed
instead of false value
* Update tests

[MODULES-2462] Improve parseyaml function

---

lib/puppet/parser/functions/parsejson.rb
lib/puppet/parser/functions/parseyaml.rb
spec/acceptance/parsejson_spec.rb
spec/acceptance/parseyaml_spec.rb
spec/functions/parsejson_spec.rb
spec/functions/parseyaml_spec.rb

Maintain the old behavior in the case where the optional second
parameter isn't passed. Also, adding arity is backwards incompatible since
stdlib still supports 2.7, so remove that.

Fix backwards compatibility from #511

---

lib/facter/service_provider.rb
spec/unit/facter/service_provider_spec.rb

This returns the default provider Puppet will choose to manage services
on this system by instantiating a dummy service resource type and
returning the provider chosen.
The original suggestion came from @asasfu but I'm not sure how to credit him.

Add a service_provider fact

---

lib/facter/package_provider.rb
spec/unit/facter/package_provider_spec.rb

This adds a package_provider fact for situations where we need to be
able to know the client's package provider in a simple way.  Situations
such as: package { 'name': install_options => [] }  As those tend to be
package provider specific options.

Add package_provider fact

---

lib/facter/package_provider.rb

#534 introduces the (re)appearance of the allow_virtual deprecation warning of packages resources with Puppet versions above 3.6 although one has
```
Package {
allow_virtual => true,
}
```
in the site.pp.
This PR fixes this by adding the allow_virtual parameter explicitly to the dummy Package if the Puppet version is 3.6 or higher.

prevent deprecation warning about the allow_virtual parameter

---

README.markdown
lib/puppet/parser/functions/bool2str.rb
spec/functions/bool2str_spec.rb

The bool2str function already exists and converts a boolean true/false to a string true/false. It is not documented in the README.
There are cases when something expects a boolean value to be something other than true/false, such as yes/no, t/f, Yes/No, on/off, etc.
This pull request add an optional two element array that bool2str will accept and convert the boolean true/false to the corresponding value in the array. If no array is given, it converts boolean true/false to a string true/false (which also preserves backwards compatibility).
Examples:
```
bool2str(true)                   => 'true'
bool2str(true, ['yes', 'no'])    => 'yes'
bool2str(false, ['t', 'f'])      => 'f' 
```

add functionality to bool2str function

---

README.markdown

Capitalize lower-cases the remaining characters (due to the Ruby function having this behavior); document this, and make minor wording tweaks.

Fix capitalize docs

---

CHANGELOG.md

This is more severe than it sounds. These characters make puppet fail with the following message : 
> Error 400 on SERVER: "\xC3" on US-ASCII

use properly encoded characters

---

lib/facter/root_home.rb
spec/unit/facter/root_home_spec.rb

The -C (capital C) flag to lsuser is incorrect. It should be -c (lowercase).
this commit updates the aix root_home fact to use `lsuser -c`, rather than `lsuser -C`.

(FM-3773) Fix root_home fact on AIX 5.x

---

lib/puppet/parser/functions/validate_ipv4_address.rb

The documentation in `validate_ipv4_address` references `validate_bool`,
but I believe this should read `validate_ipv4_address` instead, which
makes more sense.

Fix reference to validate_bool in IP4 function

---

README.markdown
lib/puppet/parser/functions/validate_ip_address.rb
spec/functions/validate_ip_address_spec.rb

Provide a validator for IP addresses, regardless they are IPv4 or IPv6

Add validator for any IP address

---

README.markdown
lib/puppet/parser/functions/seeded_rand.rb
spec/functions/seeded_rand_spec.rb

seeded_rand is needed for repeatable randomness across nodes in a cluster

(#2886) seeded_rand: new function

---

spec/acceptance/ensure_resource_spec.rb

This ensures that the test passes independently of changes to rubygems.

(FM-3802) make ensure_resource test of packages

---

lib/facter/package_provider.rb
spec/unit/facter/package_provider_spec.rb

PE 3.x emits a puppetversion fact in the format "3.x.x (Puppet Enterprise 3.x.x)". This fact causes an error when invoked on PE 3.x: Could not retrieve fact='package_provider', resolution='<anonymous>': Malformed version number string 3.8.1 (Puppet Enterprise 3.8.1
This fix has been tested on PE 3.8.2 and should work for PE 3.3, 3.7, and 3.8.
Original-fix-by: Alex Harden <aharden@gmail.com>

Allow package_provider fact to resolve on PE 3.x

---

README.markdown
lib/puppet/parser/functions/is_absolute_path.rb
lib/puppet/parser/functions/validate_absolute_path.rb
spec/unit/puppet/parser/functions/is_absolute_path_spec.rb

I really like the validate_absolute_path function and needed similar functionality to perform conditional logic on installer locations so I created the is_absolute_path function.
This uses the same code as the validate function but only accepts one argument and also returns a value.

adds new parser called is_absolute_path

---

README.markdown
lib/puppet/parser/functions/clamp.rb
spec/acceptance/clamp_spec.rb
spec/functions/clamp_spec.rb

Clamp keeps value within the range.
Employ of soft() makes the whole thing is independant of order.

Add clamp function

---

README.markdown
lib/puppet/parser/functions/validate_x509_rsa_key_pair.rb
spec/functions/validate_x509_rsa_key_pair_spec.rb

Add a function to validate an x509 RSA certificate and key pair, as
commonly used for TLS certificates.
The rationale behind this is that we store our TLS certificates and
private keys in Hiera YAML files, and poor indentation or formatting in
the YAML file could cause a valid certificate to be considered invalid.
Will cause the Puppet run to fail if:
- an invalid certificate is detected
- an invalid RSA key is detected
- the certificate does not match the key, i.e. the certificate
has not been signed by the supplied key
The test certificates I've used in the spec tests were generated using
the Go standard library:
$ go run $GOROOT/src/crypto/tls/generate_cert.go -host localhost
Example output:
==> cache-1.router: Error: Not a valid RSA key: Neither PUB key nor PRIV key:: nested asn1 …

Add a function to validate an x509 RSA key pair

---

spec/functions/basename_spec.rb

I didn't see explicit documentation on whether or not this would work, so I added a test to confirm. Test passes, so I assume this is intended behavior. A test makes this behavior explicit.

Add test for basename on path with scheme

---

lib/puppet/parser/functions/validate_ip_address.rb

The documentation in `validate_ip_address` references `validate_bool`,
but I believe this should read `validate_ip_address` instead, which
makes more sense.
Looks like this was copied from `validate_ipv4_address`, which I fixed
in 7b068781.

Fix reference to validate_bool in function

---

README.markdown
lib/puppet/parser/functions/dig.rb
lib/puppet/parser/functions/try_get_value.rb
spec/functions/dig_spec.rb

Makes deep lookup in nested hashes(and/or arrays) easier.
Usage:
dig($hash, ["key1", "key2", ...])
dig($hash, ["key1", "key2", ...], "default")
dig(
[{"a" => {"b" => "c"}}],
[0, "a", "b"]) # => "c"
Returns `nil` or optional `default` arg if at any point in the chain key couldn't be looked up.

Add dig function

---

README.markdown
lib/puppet/parser/functions/base64.rb
spec/functions/base64_spec.rb

extend base64() function to fit [rfc2045](https://www.ietf.org/rfc/rfc2045.txt) (original), and [rfc4648](https://www.ietf.org/rfc/rfc4648.txt)
allow user to specify encode/decode method to use, including "default", "strict", "urlsafe"
reference:
- [rubydoc/Base64](http://ruby-doc.org/stdlib/libdoc/base64/rdoc/Base64.html)

Extend Base64() function support

---

README.markdown
lib/puppet/parser/functions/is_ipv4_address.rb
lib/puppet/parser/functions/is_ipv6_address.rb
spec/acceptance/is_ipv4_address_spec.rb
spec/acceptance/is_ipv6_address_spec.rb

These are useful when making decisions based on the type of IP
address received.

Add is_ipv4_address and is_ipv6_address functions

---

README.markdown
lib/puppet/parser/functions/enclose_ipv6.rb
spec/unit/puppet/parser/functions/enclose_ipv6_spec.rb

Copy a function from puppetlabs/apache, created by Benedikt Bock by
https://github.com/puppetlabs/puppetlabs-apache/commit/55cc3b4e8f4bc859a1255cb57be2c7923005d822.
This function encloses IPv6 addresses in square brackets.
It takes an array of ip addresses and encloses the ipv6 addresses with
square brackets.
This Function is very useful and I would like to use it in other Puppet modules.
Co-Authored-By: Benedikt Bock <benedikt_bock@web.de>

Add enclose_ipv6 function

---

spec/acceptance/fqdn_rand_string_spec.rb

Puppet 4.4.0 and later has changed fqdn_rand to use a higher ceiling
(PUP-5646), the tests for fqdn_rand_string needed to be updated to
reflect the new expected output.

(maint) Fixes fqdn_rand_string tests

---

README.markdown
lib/puppet/parser/functions/ensure_packages.rb
lib/puppet/parser/functions/ensure_resources.rb

This change will allow to pass values from hiera backend variables as hash in first argument with additional parameters needed.
Existing implementation did not support this as it considers first argument as array by default. So, if additional parameters were needed from hash, like ex. "providers => rpm" etc, will not work. It will by default pass whole hash value as string to "ensure_resource". 
It will merge the hash values for package name (key) with defaults & pass each package name to function_ensure_resource in required format for further processing. 
Use:
hiera:
```yaml
packagelist:
ksh:
ensure: latest
mlocate: {}
myrpm:
provider: rpm
source: "/tmp/myrpm-1.0.0.x86_64.rpm"
install_options:
--prefix:
/users/home
openssl:
provider: rpm
source: "/tmp/openssl-1.0.1e-42.el7.x86_64.rpm" …
```

ensure_packages.rb: Modifed to pass hiera parameters (as hash,array) as first argument

---

README.markdown
lib/puppet/parser/functions/suffix.rb
spec/functions/suffix_spec.rb

At the moment the function prefix allows a hash as input, but the function suffix only allows arrays. This patch adds the same feature set to suffix as the function prefix already has.

improve suffix function to support the same feature set as prefix

---

lib/facter/package_provider.rb

On e.g. Ubuntu 12.04 LTS Gem is not there by default so i added a check to not fail in that fact if this is the case.

Add check if Gem is defined

---

lib/facter/facter_dot_d.rb
lib/puppet/parser/functions/hash.rb
lib/puppet/parser/functions/parsejson.rb
lib/puppet/parser/functions/parseyaml.rb
lib/puppet/parser/functions/validate_cmd.rb

Catching `Exception` is gratuitous and makes Ruby behave weirdly in case of badly timed SIGINTs, SIGTERMs etc.
All proper errors should descend from `StandardError` rather than `Exception` directly (`Puppet::Error` does this). Catching those is much less problematic.

catch StandardError rather than the gratuitous Exception

---

spec/unit/puppet/provider/file_line/ruby_spec.rb

Believe that the 'match_for_absense' should actually be 'match_for_absence'

MODULES-3201 - Fixed typo 'absense' to 'absence'

---

lib/puppet/type/file_line.rb
spec/unit/puppet/type/file_line_spec.rb

`file_line` type: During validation, do not require `line` attribute if:
* `ensure` is `absent`,
* `match` is not empty,
* and `match_for_absence` is `true`.
Also update `spec` tests to reflect this.

[MODULES-2370] file_line.rb: Fix `line` attribute validation

---

lib/puppet/parser/functions/concat.rb
spec/acceptance/concat_spec.rb
spec/functions/concat_spec.rb

85d5ead Updated the concat function so that it wouldn't modify the
original array. A side-effect of this change is that it now always calls
`Array()` on the second argument. If thit is a Hash, this results in
`to_a` being called on the hash, which converts it to an array or
tuples. This is undesired.
Update the behaviour so that it doesn't (indirectly) call `to_a` on
anything, instead test for the type of the argument, wrapping it in an
array if it's not already an array.

(MODULES-3246) Fix concat with Hash arguments.

---

CHANGELOG.md
README.markdown
lib/puppet/parser/functions/delete.rb
spec/functions/delete_spec.rb

This changed exact matches to regex/substring matches in the default case, so backing out for the release.

Undo changing delete() to delete regex matches

---

README.markdown
lib/puppet/parser/functions/shell_escape.rb
lib/puppet/parser/functions/shell_join.rb
lib/puppet/parser/functions/shell_split.rb
spec/functions/shell_escape_spec.rb
spec/functions/shell_join_spec.rb
spec/functions/shell_split_spec.rb

This change adds three new functions based on [Shellwords](http://ruby-doc.org/stdlib-2.3.0/libdoc/shellwords/rdoc/Shellwords.html):
* `bourne_shell_escape(string)` (`Shellwords.shellescape`)
* `bourne_shell_join(array)` (`Shellwords.shelljoin`)
* `bourne_shell_split(string)` (`Shellwords.shellsplit`)
I seem to be repeating these escape and join functions in a lot of my modules. I've also hit shell escaping issues while using a few popular modules from the forge. I've included the split function for the sake of completeness.

Expose the functions of ruby's built-in Shellwords module

---

README.markdown
lib/puppet/parser/functions/delete.rb
spec/functions/delete_spec.rb

Ping @hunner.
@smoeding alerted me to this problem.

Use reject instead of delete_if

---

lib/puppet/parser/functions/any2bool.rb
spec/functions/any2bool_spec.rb

* Basically a combination of `string2bool` and `num2bool`
So there's a request for this to be added to stdlib (https://tickets.puppetlabs.com/browse/MODULES-1439).
Questions:
* Do we want to muddle the waters by the string casting to numeric part to the check? So should '-1' be true because it's a string, or false because when num2bool its false?
* There's already a `any2bool` as part of [puppi](https://github.com/example42/puppi/blob/master/lib/puppet/parser/functions/any2bool.rb), should we give this a different name?

(MODULES-1439) Adds any2bool function

---

lib/puppet/parser/functions/validate_email_address.rb

Otherwise you get this on 1.8.7:
```
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /usr/share/foreman-installer/modules/stdlib/lib/puppet/parser/functions/validate_email_address.rb:2: syntax error, unexpected ':', expecting ')' (SyntaxError)
newfunction(:validate_email_address, doc: <<-ENDHEREDOC
```

(MODULES-3354) Use 1.8.7 hash in validate_email_address function

---

README.markdown
lib/puppet/parser/functions/loadjson.rb
spec/acceptance/loadjson_spec.rb
spec/acceptance/loadyaml_spec.rb
spec/functions/loadjson_spec.rb

This value will be returned if the is no file to load or a file could not be parsed.
It's similar to the "parseyaml" function's default value.
Add the "loadjson" function too.

Add the default value to the "loadyaml" function

---

README.markdown
lib/puppet/parser/functions/delete.rb
lib/puppet/parser/functions/delete_regex.rb
spec/functions/delete_regex_spec.rb

To maintain backwards compatibility, add a third parameter to the delete
function to specify what type the second should be interpreted as. This
is needed for cases where the regex matcher is overzealous.
This was uncovered while testing this against @smoeding's sendmail module as seen here:
https://github.com/smoeding/puppet-sendmail/issues/8

Add delete_regex

---

lib/puppet/parser/functions/defined_with_params.rb
spec/functions/defined_with_params_spec.rb
spec/functions/ensure_resource_spec.rb

As described in PUP-6422,
ensure_resources('File[/tmp/a]', { owner => undef })
would not actually create the file. This fixes it, and adds tests to prove
it.

(MODULES-3543) Fix define_with_params to handle undef properly

---

README.markdown
lib/puppet/parser/functions/dig.rb
lib/puppet/parser/functions/dig44.rb
spec/functions/dig44_spec.rb
spec/functions/dig_spec.rb

A new version of dig was introduced in Puppet 4.5.0 that
isn't compatible with the stdlib version of dig. To maintain
backwards compatibility and ensure that tests for stdlib aren't
broken, this patch renames dig to dig44 and adds a deprecation
warning to the stdlib dig function.

(MODULES-3568) Move dig to dig44 and deprecate dig

---

spec/functions/ensure_resource_spec.rb

This updates the test to match the new behaviour in puppet 4.6.0

(MAINT) Update ensure_resource specs

---

lib/puppet/parser/functions/deprecation.rb
spec/functions/deprecation_spec.rb
spec/functions/is_array_spec.rb
spec/functions/is_bool_spec.rb
spec/functions/is_float_spec.rb
spec/functions/is_integer_spec.rb
spec/functions/is_numeric_spec.rb
spec/functions/is_string_spec.rb
spec/functions/validate_absolute_path_spec.rb
spec/functions/validate_array_spec.rb
spec/functions/validate_bool_spec.rb
spec/functions/validate_integer_spec.rb
spec/functions/validate_numeric_spec.rb
spec/functions/validate_re_spec.rb
spec/functions/validate_string_spec.rb

The deprecation function was calling the `Kernel#warn` function which
prints to stderr, rather than the Puppet logger. This causes problems
for Puppet module tests on Travis CI, which has a cap on the amount of
stdout/err permitted in its logs and also prevents users from finding
the deprecation warnings when running under a Puppet master.

(maint) Switch 3.x deprecation() to use Puppet warning logger

---

spec/acceptance/deprecation_spec.rb

1. The manifest containing the deprecation function needed to be modified (surrounded in double quotes) to work as a puppet apply command on windows. 
2. "exist" was not working on Solaris 10 because the underlying command doesn't actually exist on Solaris 10, so I changed it to "be_file" which works just fine for this. 
3. Added conditional logic to accommodate Windows paths.

MODULES-3699 Deprecation spec fix 2

---

README.markdown

This is a minor update in the README to state that the validate_numeric function also supports a numerical string.

Change in readme for numerical string

---

lib/puppet/parser/functions/dig44.rb
spec/functions/dig44_spec.rb

The current implementation of the dig44 function has the
following problems:
* Doesn't recognise Puppet4's :undef value as an empty value
and doesn't return the default value.
* Doesn't make a different between false and nil value
and returns the default value for a non-empty false value

Refactor dig44 function

---

lib/puppet/parser/functions/validate_string.rb
spec/acceptance/is_string_spec.rb
spec/acceptance/validate_string_spec.rb
spec/aliases/string_spec.rb
spec/functions/validate_string_spec.rb
types/compat/string.pp

When validate_string is called via the Puppet 4 deprecation wrappers
from deprecation_gen (introduced in 970852d), `undef` is passed as `nil`
where it was previously passed as `''` from the Puppet 3-style function
API.
This change explicitly permits a `nil` value in validate_string, and
adds a test case to `is_string` which also accepts the same.
Fixes test failures in apt, concat etc:
Error while evaluating a Function Call, nil is not a string.  It looks to be a NilClass at apt/manifests/source.pp:23:3 [..]
(Introduced by #659)

Permit undef passed as `nil` to validate_string

---

lib/puppet/parser/functions/getvar.rb

`catch` returns value of second argument to `throw`, which until https://github.com/puppetlabs/puppet/commit/860a2761f334c964068038b3ef6853f08beb1df5#diff-bb62983f077c2b43d065be52de182209R514 was `nil`, but now is non-falsey reason for error. short-circuit using return and eval to nil if `throw` was caught.

Ignore :undefined_variable "reason" in getvar

---

README.markdown

Update the README to specify that the 'after' parameter in
the file_line resource accepts a regular expression.

(MODULES-3407) Clarify that 'after' in file_line accepts regex.

---

.travis.yml
CHANGELOG.md
lib/puppet/functions/is_absolute_path.rb
lib/puppet/functions/is_array.rb
lib/puppet/functions/is_bool.rb
lib/puppet/functions/is_float.rb
lib/puppet/functions/is_ip_address.rb
lib/puppet/functions/is_ipv4_address.rb
lib/puppet/functions/is_ipv6_address.rb
lib/puppet/functions/is_numeric.rb
lib/puppet/functions/is_string.rb
lib/puppet/functions/validate_absolute_path.rb
lib/puppet/functions/validate_array.rb
lib/puppet/functions/validate_bool.rb
lib/puppet/functions/validate_hash.rb
lib/puppet/functions/validate_integer.rb
lib/puppet/functions/validate_ip_address.rb
lib/puppet/functions/validate_ipv4_address.rb
lib/puppet/functions/validate_ipv6_address.rb
lib/puppet/functions/validate_legacy.rb
lib/puppet/functions/validate_numeric.rb
lib/puppet/functions/validate_re.rb
lib/puppet/functions/validate_slength.rb
lib/puppet/functions/validate_string.rb

This is a workaround for PUP-4438 (fixed in https://github.com/puppetlabs/puppet/commit/e01c4dc924cd963ff6630008a5200fc6a2023b08, 4.1.0, 3.8.1).
It works by manually passing through the scope, instead of relying on the
InternalFunction class.

(MODULES-3962) Rework v4 function shims to work on puppet 3.7 and 4.0.0

---

README.markdown

The README references the environment variable `STDLIB_LOG_DEPRECATION` while the code uses `STDLIB_LOG_DEPRECATIONS` (note the trailing S).

Fix incorrect environment variable name in README

---

lib/puppet/parser/functions/ensure_resources.rb

This function otherwise fails during `puppet preview` on Puppet 3.8.X systems.

(MODULES-3829) Use .dup to duplicate classes for modification.

---

spec/functions/validate_legacy_spec.rb

These were caused by a change in the tested error message.

Fix spec failures on puppet 4.8

---

README.markdown

Doc link to the validate_legacy section is missing an underscore which is a little annoying.

Fixing broken link to #validate_legacy docs

---

lib/puppet/parser/functions/deprecation.rb

Without this, some uses of this function do not work in puppet3. e.g.
if $include_src != undef {
deprecation('apt $include_src', "please use \$include => { 'src' => ${include_src} } instead")
}
causes
Function 'deprecation' must be the value of a statement
on puppet 3.8.7.

Remove rvalue declaration from v3 deprecation() function

---

README.markdown
lib/puppet/functions/type_of.rb

Prior to this commit, users coming to the type_of function would not realize that the type function in puppet does the same thing and is preferred over type_of. 
After this commit, we have a comment indicating the above.

Indicate that the type function is preferred

---

CHANGELOG.md
metadata.json

The previous release prep accidentally had 4.13.2 instead of 4.14.0 as is appropriate with releases with features. This is a PR to rectify that. No 4.13.2 release or tag will be made. The 4.14.0 release will go ahead instead.

Release prep for 4.14.0

---

lib/puppet/parser/functions/ensure_packages.rb
spec/fixtures/test/manifests/ensure_resources.pp
spec/functions/ensure_packages_spec.rb
spec/unit/ensure_resources_spec.rb

Prior to this commit, we didn't have tests for the ensure_resources
function (only for the ensure_resource function). This meant that
we weren't catching a bug in the ensure_resources function. In order
to prevent this in the future, add some tests which test the
specific functionality of ensure_resources.

(MODULES-3829) Add tests for ensure_resources

---

README.markdown
lib/puppet/parser/functions/fqdn_uuid.rb
spec/functions/fqdn_uuid_spec.rb

* Generates UUID based on a given string and 
optional seed

(MODULES-4188) Add UUID generation function

---

README.markdown
lib/puppet/parser/functions/pry.rb

Add pry() function from hunner-pry

---

lib/facter/puppet_settings.rb

It is frequently useful to configure an agent to retrieve a resource
from it's configured master, or make further configuration adjustments
to itself based on what server it's using. Similar to the rationale for
stdlib providing a puppet_vardir fact, this commit adds a puppet_server
fact.
Note that the closest equivalent available today is $settings::server,
which returns only the MASTER's configured server, not the AGENT's. This
makes $settings::server unreliable, and not useful in a multi-master
deployment or a deployment involving a load balancer.

Add puppet_server fact to return agent's server

---

spec/functions/has_ip_network_spec.rb

The symbol used in the value of the facts hash is not a valid type of
value for facts, and results in the following error since
rspec-puppet@d50acf0e.
Puppet::Error:
Unsupported data type: 'Symbol'
The fact's presence doesn't change the behaviour, so remove it.

Fix unsupported data type error with rspec-puppet master

---

spec/acceptance/zip_spec.rb
spec/spec_helper_acceptance.rb

Due to [BKR-969](https://tickets.puppetlabs.com/browse/BKR-969) the global `Hiera` symbol is corrupted. Loading puppet before beaker fixes that.

Fix acceptance test failure "Hiera is not a class"

---

spec/functions/load_module_metadata_spec.rb
spec/functions/loadjson_spec.rb

Since puppetlabs/puppet@f2e8e66, the test module's metadata.json is also
read causing expectation failures. Like 5c51463, permit it to be read by
Puppet.

Allow test module metadata.json to be read

---

spec/functions/delete_undef_values_spec.rb
spec/functions/difference_spec.rb
spec/functions/flatten_spec.rb
spec/functions/fqdn_rand_string_spec.rb
spec/functions/fqdn_rotate_spec.rb
spec/functions/grep_spec.rb
spec/functions/hash_spec.rb
spec/functions/intersection_spec.rb
spec/functions/join_keys_to_values_spec.rb
spec/functions/join_spec.rb
spec/functions/lstrip_spec.rb
spec/functions/member_spec.rb
spec/functions/pick_default_spec.rb
spec/functions/prefix_spec.rb
spec/functions/reject_spec.rb
spec/functions/reverse_spec.rb
spec/functions/rstrip_spec.rb
spec/functions/size_spec.rb
spec/functions/strip_spec.rb
spec/functions/suffix_spec.rb
spec/functions/union_spec.rb
spec/functions/unique_spec.rb

This is unit tests for the low effort function tests for i18n compatibility. 
This includes tests for the following functions:
delete_undef_values
difference
flatten
fqdn_rand_string
fqdn_rotate
grep
hash
intersection
join
join_keys_to_values
lstrip
member
merge
pick_default
prefix
reject
reverse
rstrip
strip
suffix
union
unique

(FM-6054) - Unit tests for low effort functions

---

spec/functions/basename_spec.rb
spec/functions/chomp_spec.rb
spec/functions/chop_spec.rb
spec/functions/deep_merge_spec.rb
spec/functions/dirname_spec.rb
spec/functions/fqdn_uuid_spec.rb
spec/functions/getvar_spec.rb
spec/functions/has_key_spec.rb
spec/functions/is_a_spec.rb
spec/functions/pick_spec.rb
spec/functions/regexpescape_spec.rb
spec/functions/shell_escape_spec.rb
spec/functions/shell_join_spec.rb
spec/functions/shell_split_spec.rb
spec/functions/shuffle_spec.rb
spec/functions/values_at_spec.rb
spec/functions/values_spec.rb
spec/functions/zip_spec.rb

This contains unit tests for to check for UTF8 and double byte character compatibility for the medium effort functions.
Tests for the following functions are included:
1. - basename
2. - chop
3. - chomp
4. - deep_merge
5. - dirname
6. - getvar
7. - has_key
8. - is_a
9. - pick
10. - assert_private
11. - shell_escape
12. - shell_join
13. - shell_split
14. - shuffle
15. - values
16. - values_at
17. - zip

(FM-6058) - Unit tests for med effort functions

---

spec/acceptance/type_spec.rb

now handles type is Tuple[String[3, 3], String[6, 6], String[3, 3], String[9, 9]] and Tuple[String, String, String, String]

loosen the regex for tuple checking

---

lib/puppet/parser/functions/ensure_packages.rb

As there is a number of modules that use ensure_package without wrapping a defined around them many modules have conflicts. This will help work around them by default, Puppet will not let you define a resource twice so it should be done here as well

Should only try to apply the resource if it not defined

---

README.markdown
lib/puppet/provider/file_line/ruby.rb
lib/puppet/type/file_line.rb
spec/unit/puppet/type/file_line_spec.rb

Add a new parameter `encoding` to allow non UTF-8 files to specify a file encoding.  This prevents receiving the error message "invalid byte sequence in UTF-8" when special characters that are not UTF-8 encoded appear in the input stream, such as the copyright symbol.

(#FM-6068) allow file encoding to be specified

---

README.markdown
lib/puppet/parser/functions/base64.rb
lib/puppet/parser/functions/camelcase.rb
lib/puppet/parser/functions/capitalize.rb
lib/puppet/parser/functions/delete_regex.rb
lib/puppet/parser/functions/downcase.rb
lib/puppet/parser/functions/pw_hash.rb
lib/puppet/parser/functions/sort.rb
lib/puppet/parser/functions/str2saltedsha512.rb
lib/puppet/parser/functions/strftime.rb
lib/puppet/parser/functions/swapcase.rb
lib/puppet/parser/functions/upcase.rb
lib/puppet/parser/functions/uriescape.rb

Add comments detailing which functions may not be fully UTF8 compatible. Also adds the camelcase readme entry.

(FM-6051) Adds comments to warn for UTF8 incompatibility

---

spec/aliases/absolute_path_spec.rb
spec/aliases/absolutepath_spec.rb
spec/aliases/array_spec.rb
spec/aliases/bool_spec.rb
spec/aliases/float_spec.rb
spec/aliases/hash_spec.rb
spec/aliases/httpsurl_spec.rb
spec/aliases/httpurl_spec.rb
spec/aliases/integer_spec.rb
spec/aliases/ip_address.rb
spec/aliases/ipv4_spec.rb
spec/aliases/ipv6_spec.rb
spec/aliases/numeric_spec.rb
spec/aliases/string_spec.rb
spec/aliases/unixpath_spec.rb
spec/aliases/windowspath_spec.rb
spec/functions/deprecation_spec.rb
spec/functions/ensure_resource_spec.rb
spec/functions/validate_legacy_spec.rb

`Puppet.version.to_f` on Puppet 4.10.0 will evaluate to `4.1`, causing
test and behavioural changes when conditionals check that the version is
equal or greater than versions such as `4.3`.
Version comparisons that are vulnerable to this have been changed to use
Puppet's versioncmp implementation, while most others only check for
for major version boundaries which is safe.

(MODULES-4528) Use versioncmp to check Puppet version for 4.10.x compat

---

spec/aliases/string_spec.rb

The fix for PUP-7371 adds the missing `Undef` into the error message
being tested in type aliases specs, fixing the following failure against
Puppet's master branch:
test::string rejects other values [] should fail to compile and raise an error matching /parameter 'value' expects a String/
Failure/Error: it { is_expected.to compile.and_raise_error(/parameter 'value' expects a String/) }
error during compilation: Evaluation Error: Error while evaluating a Resource Statement, Class[Test::String]: parameter 'value' expects a value of type Undef or String, got Array at line 2:1 on node example

Update alias spec error message expectation for PUP-7371

---

README.markdown
lib/puppet/parser/functions/glob.rb
spec/functions/glob_spec.rb

Add glob function

---

README.markdown

Hello good module people!
Please carefully review my changes here. I've noted all questions or places I'm in doubt about with TODO, so you can search for that to find those spots easily.

(MODULES-4322) pre-loc edit on stdlib README

---

README.markdown

Add TOC entries for the various reference sections, plus a markdown-related typo in a header

TOC updates

---

lib/puppet/parser/functions/defined_with_params.rb
spec/functions/defined_with_params_spec.rb

- `defined_with_params` calls `findresource(reference.to_s)`
- `findresource` is
https://github.com/puppetlabs/puppet/blob/4.8.1/lib/puppet/parser/compiler.rb#L407
and points to
https://github.com/puppetlabs/puppet/blob/4.8.1/lib/puppet/resource/catalog.rb#L352
- This calls `Puppet::Resource.new` with the type
https://github.com/puppetlabs/puppet/blob/4.8.1/lib/puppet/resource/catalog.rb#L366
- This ends up calling `resource_type` via
https://github.com/puppetlabs/puppet/blob/4.8.1/lib/puppet/resource.rb#L317-L319
and that ends up declaring the type via the autoloader api at
https://github.com/puppetlabs/puppet/blob/4.8.1/lib/puppet/resource.rb#L390
- But why does the autoloader API fail to find it in the current
environment?
- Okay, so when the autoloader is trying to find the type, it …

(PE-20308) Pass a literal type and not a string to findresource

---

README.markdown

This causes issues with displaying a Japanese translation. It struggles
rendering the `) therefore removing italics.

Removing italics for 'undef' value

---

README.md

Formatting fixes, mostly in file_line defined type, but I found a rando header that was too big as well.

(FM-6197) formatting fixes for file_line resource

---

lib/puppet/parser/functions/defined_with_params.rb

This commit adds a simple workaround for the problem described in
PUP-7650. The workaround is harmless and can remain in place regardless
of if the fix for PUP-7650 is in place or not.

(MODULES-5095) Workaround for PUP-7650

---

lib/puppet/type/file_line.rb

Do this by making it a property. The idea is to get rid of the warning
that appears when a Sensitive value is passed to the line attribute.

(MODULES-5113) Make line support Sensitive

---

lib/puppet/provider/file_line/ruby.rb
spec/unit/puppet/provider/file_line/ruby_spec.rb

If the following lines exist
hard core 90
hard core 10
it correctly corrects both lines to
hard core 0
hard core 0
However if these lines exist in the file
hard core 90
hard core 0
It incorrectly does nothing 
It should correct the first line

(MODULES-5003) file_line fix all broken lines

---

lib/puppet/parser/functions/ensure_packages.rb
spec/functions/ensure_packages_spec.rb

If user declares ensure_packages(<Package>, { ensure => 'present' }) and ensure_packages(<Package>, { ensure => 'installed' }) concurrently, funcion fails at different 'ensure' values. This change causes function to change 'installed' to 'present', avoiding this error.
Maybe similar treatment is needed when arguments[0] is a hash, but I'm an absolute beginner in Ruby.

(Modules 4377) Causes ensure_packages to accept concurrent declarations with ensure => 'present' and 'installed'

---

lib/puppet/provider/file_line/ruby.rb
spec/unit/puppet/provider/file_line/ruby_spec.rb

The exists? method is called to determine the need to call the create and
destroy methods. When the :ensure, :match, and :multiple attributes are defined,
the exists? method needs to return false unless all the lines that match the
:match attribute are equal to the :line attribute.
The first commit is minimal, and implements this change.
The second commit normalizes the code, which I needed for comprehension.
Either resolves the issue.

(MODULES-5003) file_line does not change multiple lines when one matches

---

lib/puppet/parser/functions/pw_hash.rb
spec/aliases/integer_spec.rb
spec/functions/pw_hash_spec.rb

Also includes a small fix to integer_spec so tests pass.

(MODULES-4908) adds support for sensitive data type to pw_hash

---

lib/puppet/functions/fact.rb

This PR doesn't solve for FACT-932, but is related to it and discussion
there.
The fact() function allows dot-notation reference to facts. It is an
alternative to using $facts directly with array-indexing. Array-indexing
is often onerous to use since it doesn't align with how structured facts
are accessed elsewhere in the ecosystem and if any element in a
multi-step path doesn't exist, array indexing can cause a compilation
failure.
Example usage:
fact('os.family')

(FACT-932) Add new function, fact()

---

README.md

Add README update for `fact()` function. This was missed in #787.

Update README for fact() function

---

README.md
lib/puppet/provider/file_line/ruby.rb
lib/puppet/type/file_line.rb
spec/unit/puppet/provider/file_line/ruby_spec.rb

Currently, there doesn't exist a way to leave a file untouched if no regex matches are found. 
I have a use case where I'm searching for a specific regex in multiple files and I only want to update the files that contain the regex pattern.

Add new file_line option append_on_no_match

---

README.md
lib/puppet/parser/functions/validate_domain_name.rb
spec/functions/validate_domain_name_spec.rb

Add validate_domain_name function.

Add validate_domain_name function

---

metadata.json

puppet version requirement lower bound was accidentally moved to 4.7.0 without a major bump. this returns the lower bound to 2.7 but also pushes the upper bound to include puppet 5.

(maint) revert puppet version requirement

---

README.md
lib/puppet/functions/to_json.rb
lib/puppet/functions/to_json_pretty.rb
lib/puppet/functions/to_yaml.rb
spec/functions/to_json_pretty_spec.rb
spec/functions/to_json_spec.rb
spec/functions/to_yaml_spec.rb

In ERB, it was easy to do:
```ruby
<%= @hash.to_json %>
```
...but now with EPP, we cannot call on ruby.  We need to access this through Puppet functions.
https://tickets.puppetlabs.com/browse/MODULES-5386

Added to_json, to_json_pretty, and to_yaml functions

---

lib/puppet/parser/functions/pw_hash.rb

Older versions of Puppet end up choking on the sensitive data type check in the pw_hash function added in 42d4ea7. this adds a check for the Sensitive class and then the type of the arg, so that if the class has not been declared, it will just move on.

(MODULES-5546) add check for pw_hash

---

README.md

I used the example code from this README file with our puppet code but i got downvotes from CI / jenkins / puppet-lint because it doesn't conform to Puppet style guides to use double quotes here.
It produces "double quoted string containing no variables" warnings from puppet-lint.
I wanted to fix the example locally but it was pointed out to me we should fix it upstream stdlib instead, so here it is. Just use single quotes here.

use single quotes in validate_legacy example code

---

types/unixpath.pp

Since the purpose of this validation type is to check if the given parameter is a valid UNIX path it should also cover the root path "slash" since it might be possible that it is specified as a target directory.

Allow root as valid UNIX path

---

README.md
lib/puppet/type/file_line.rb
spec/unit/puppet/provider/file_line/ruby_spec.rb
spec/unit/puppet/type/file_line_spec.rb

Based on a Stack Overflow question, it was noted that the documentation
for `file_line` isn't complete and the underlying behaviour somewhat
confusing.
https://stackoverflow.com/questions/46468922/how-to-change-the-contents-of-a-file-by-using-puppet/46473458
In this patch I add additional unit tests and better examples and
complete documentation.

(maint) Clarify docs and add new tests

---

README.md
lib/puppet/provider/file_line/ruby.rb
lib/puppet/type/file_line.rb
spec/unit/puppet/provider/file_line/ruby_spec.rb

https://tickets.puppetlabs.com/browse/MODULES-5003 gave rise to #788 and #794 which caused different behavior based on whether the line value was matched by the match regex or not.
The change in behavior was both breaking and broken, though that was hard to tell because the behavior was ill-described in general.
[bugfix] This commit resolves the breaking behavior by reverting the behavior of "replacing matches when a line matching `line` exists even when `multiple` is set to `true`".
[feature] This commit adds a new parameter to make file_line replace all matches universally with the `line` value, even when the line exists elsewhere in the file. This feature only affects modifying multiple lines in a file when the `line` value already exists.
[bugfix] This commit more strictly defines the …

(MODULES-5651) Do not append infinitely

---

metadata.json

Removal of Redhat 4, Centos 4, Oracle Linux 4, Scientific Linux 4, Sles
10, Windows 2003 and Windows 2003 r2.
Addition of Debian 9.
Updates are according to: https://puppet.com/docs/pe/2017.3/installing/supported_operating_systems.html

Updates to metadata.json

---

lib/puppet/type/file_line.rb

(maint) Fix example syntax

---

README.md

A few docs fixes before we send it off for translation updates.

README fixups for 4.21.0 release

---

spec/unit/puppet/provider/file_line/ruby_spec.rb

When working with "file_line" and "ensure=>absent", I noticed that my existing manifests that were perfectly fine in 4.18.0, stopped working in 4.19.0. Digging deeper into the issue, I was able to identify commit 81d7d35fd789 that caused the problem. In order to provide a minimal working example to describe the issue, I stumbled over the example from the "README.md":
```
file_line { 'bashrc_proxy':
ensure             => present,
path               => '/etc/bashrc',
line               => 'export HTTP_PROXY=http://squid.puppetlabs.vm:3128',
match              => '^export\ HTTP_PROXY\=',
append_on_no_match => false,
}
```
I found out, that this example only works when the line to remove is exactly "export HTTP_PROXY=http://squid.puppetlabs.vm:3128" and does not do anything for a line like …

correct test cases to properly check result

---

README.md
lib/puppet/functions/ifelse.rb
spec/functions/ifelse_spec.rb

Allows for more compact, clean code.

(MODULES-5679) Add a new function ifelse to match ruby's tenary operator

---

README.md
lib/puppet/functions/sprintf_hash.rb
spec/functions/sprintf_hash_spec.rb

(MODULES-5680) Added new function sprintf_hash to allow using named references

---

README.md

some docs fixups before release

fixups on stdlib README

---

.sync.yml

Fix the indentation of the `rubocop` test in the `.travis.yml` `extras`
section.  Also replace unicode `EN SPACE` characters with ASCII spaces.

MODULES-6106: Fix broken `.sync.yml`

---

lib/puppet/functions/to_json_pretty.rb
spec/functions/to_json_pretty_spec.rb

Note that I also added a trailing newline at the end of `to_json_pretty()` output. Seems like a desirable change since usually we output to a file.

Ability to skip undef values in to_json_pretty()

---

lib/puppet/parser/functions/type.rb
lib/puppet/parser/functions/type3x.rb
spec/acceptance/type3x_spec.rb

This has been introduced with implementing Rubocop: https://github.com/puppetlabs/puppetlabs-stdlib/pull/838

(MODULES-6216) - Fix type3x function in stdlib

---

types/unixpath.pp

https://tickets.puppetlabs.com/browse/MODULES-6221

fixed wrong comment in unixpath.pp

---

lib/puppet/parser/functions/join_keys_to_values.rb

support flags
```
gitlab_ci_runners_defaults:
tag-list: 'custom'
run-untagged:
executor: 'shell'
```
(gitlab module joins on space)
would become:
`--tag-list custom --run-untagged --executor shell`
the `--run-untagged` does not accept values.
Because puppet and hieradata returns string values i had to use `String(v) == "undef"`.  
I couldn't get it to work with `not defined?(v)` or `v.nil?`.

Handle join_keys_to_values() with undef values.

---

lib/puppet/parser/functions/type3x.rb

stdlib/lib/puppet/parser/functions/type3x.rb:25: warning: constant ::Fixnum is deprecated
stdlib/lib/puppet/parser/functions/type3x.rb:25: warning: constant ::Bignum is deprecated

get rid of fixnum|bignum deprecation warning

---

README.md

These changes includes:
1.  The removal of 'Unacceptable Examples' to avoid confusion
2. The removal of hard line breaks
3. The addition of 'valid values'
4. Changing IP Addresses wrapped in back ticks to wrap them in single quotes
These changes are being PR'd directly against the release branch as these are required before the module can be released.

(MODULES-6771) - Updates to README.

---

README.md

Just one teeny tiny fix; this came up in translation and Transifex is already fixing it in the Japanese version. No retranslation needed for this PR.

fix minor README error to align with JP translation

---

lib/puppet/parser/functions/type3x.rb

Reverts puppetlabs/puppetlabs-stdlib#875
@tuxmea I would just like to thank you for taking the time to make this change. However as an oversight from our end we are only testing on Puppet4 and this change breaks tests on Puppet5. This is something that we are currently looking into rectifying. Apologies for the revert, but again thank you for taking the time to contribute it is really appreciated. 
The Modules Team.

(maint) - Revert "get rid of fixnum|bignum deprecation warning"

---

README.md
lib/puppet/parser/functions/loadjson.rb
lib/puppet/parser/functions/loadyaml.rb
spec/functions/loadjson_spec.rb
spec/functions/loadyaml_spec.rb

This functionality is useful if one needs to interface their puppet manifest with external systems that expose hashes via JSON or YAML over HTTP(S).

Load https file into loadjson() and loadyaml()

---

README.md

Prior to this commit, all links to documentation were aiming at docs.puppet.com URLs.  While most are redirected by that web server to the correct puppet.com/docs equivalent, several were not.  This commit updates old docs.puppet.com URLs with their corresponding puppet.com/docs URL.

Update docs.puppet.com URLs to be puppet.com/docs

---

README.md
spec/acceptance/size_spec.rb

This fix is required as the size function has been put into puppet from puppet 6.0.0. The function in puppet 6 and greater will take precendence over the one in stdlib therefore our tests are no longer relevant for versions of puppet 6 and above.
I have tested this function locally to ensure that the tests continue to run on versions less than puppet 6.0.0 and no longer run on versions 6.0.0.
I can confirms tests continue to run on puppet versions less than puppet 6.0.0 and no longer run on puppet version 6.0.0.
```
=>  5: describe 'size function', :if => Puppet::Util::Package.versioncmp(Puppet.version, '6.0.0') < 0 do
6:   describe 'success' do
7:     pp1 = <<-DOC
8:       $a = 'discombobulate'
9:       $o = size($a)
10:       notice(inline_template('size is <%= @o.inspect %>'))
[1] …
```

(PUP-8605) - Update acceptance tests and README for size function

---

spec/acceptance/size_spec.rb

This function will be present in core puppet from version 6.0.0 and later.

(maint) - Skip sort when puppet agent is version 6 or greater

---

lib/puppet/parser/functions/pick.rb
spec/functions/pick_spec.rb

If `strict_variables` is enabled, then the standard usage of `pick()`
will fail. This simply adds the calling convention that strings that
look like variables will be resolved if they exist and ignored if they
don't.

Allow pick() to work with strict variables

---

lib/puppet/parser/functions/pick.rb
spec/functions/pick_spec.rb

This reverts commit 2a493adcd01ece80cb70fab004e2fb8b01261775.
This change was not backwards compatible. If a user was using pick with
a string that include a $, it would be evaluated and could throw an
error.
See https://bugs.launchpad.net/tripleo/+bug/1778201

Revert "Allow pick() to work with strict variables"

---

lib/puppet/parser/functions/any2array.rb
spec/functions/any2array_spec.rb

any2array currently returns an array containing the empty string, when
given the empty string.
Example:
```
any2array('').each |$e| {
notice('I\'m not empty!')
}
```
This is counter intuitive, as Puppet considers the empty string as
Strings nil value, for which the equivalent Array is the empty array.
This especially apparent when doing a lookup in a map with a non
existing key.
Example:
```
$config = {}
any2array($config['test']).each |$e| {
notice('I\'m not empty!')
}
```
Both these cases print the string `I'm not empty`, this PR fixes that.

Make any2array return empty array on empty string

---

lib/puppet/functions/sprintf_hash.rb

The functions was already documented as being deprecated but an actual
call was missing. This commit adds a call.
Note that the sprintf_hash function is a 4.x function and therefore uses
call_function (all other functions use the deprecated `function_<name>`
convention. They also send Ruby Symbol as the name of the function.

(maint) Add deprecation call to `sprintf_hash`

---

README.md
lib/puppet/functions/seeded_rand_string.rb
spec/functions/seeded_rand_string_spec.rb

This function is useful for generating consistent random strings (read "passwords") across different nodes.

seeded_rand_string() function

---

lib/puppet/parser/functions/delete_undef_values.rb
spec/functions/delete_undef_values_spec.rb

PUP-9112 changed use of `:undef` inside structured values to instead
using `nil` in Puppet 6.0.0. The `delete_undef_values()` function
was not prepared to handle this and would not delete `nil` from
`Array` or `Hash` values.
This commit fixes this problem.
All 3.x functions in stdlib were reviewed for the same problem, and only `delete_undef_values()` had this problem.

(MODULES-7768) Handle nil in delete_undef_values() function

---

lib/puppet/parser/functions/pick.rb
lib/puppet/parser/functions/pick_default.rb

In puppet, (since version 4 or 3 with future parser), the only values
that are falsey are `undef` and `false`.

Fix `pick` function docs

---

lib/puppet/parser/functions/is_mac_address.rb
spec/acceptance/is_mac_address_spec.rb
spec/functions/is_mac_address_spec.rb
types/mac.pp

Not quite sure if the best thing is to extend the MAC matcher, but since the 20-octet hardware address is the exact same format it feels like a good start.

(MODULES-7024) Add 20-octet MAC addresses

---

lib/puppet/parser/functions/ensure_packages.rb

Instead of just looking for an already existing package resource with
the same name, we should check for the parameters, too. Otherwise having
one ensure_packages call with ensure => present and one with ensure =>
absent leads to the second function call being ignored. It should throw
a duplicate declaration error instead.
Since we are already calling ensure_resource internally and
ensure_resource itself does check for duplicates, we don't need that
extra check in ensure_packages.

fix ensure_packages duplicate checking

---

README.md
lib/puppet/functions/os_version_gte.rb
spec/functions/os_version_gte_spec.rb

This function aims to reduce the boiler plate that a lot of modules have
to compare versions:
if $facts['operatingsystem'] == 'Ubuntu' && versioncmp(facts['operatingsystemmajrelease'], '16.04') >= 0 {
Can now be reduced to:
if os_version_gte('Ubuntu', '16.04') {
Let the bikeshedding commence!

Add a function to compare the OS version

---

README.md

This commit adds HTML anchor tags to improving the localization.

(maint) - Add HTML anchor tag

---

lib/puppet/parser/functions/defined_with_params.rb
spec/acceptance/defined_with_params_spec.rb
spec/functions/defined_with_params_spec.rb

This change ensures that unquoted classes are correctly checked.

(MODULES-8273) - Make unquoted classes useable

---

spec/type_aliases/filesource_spec.rb
types/filesource.pp

The previous regex only supported the special `modules` `puppet:///`
mount point.  Custom mount points should also be accepted.
https://puppet.com/docs/puppet/5.5/file_serving.html#whats-a-mount-point-in-a-puppet-uri

(MODULES-8404) - Relax `Stdlib::Filesource` type

---

README.md

In the type the casing is HTTPUrl and HTTPSUrl. This matches the docs to reality.

(maint) Match HTTP[S]Url case to the actual types

---

README.md
lib/puppet/functions/merge.rb
spec/functions/merge_spec.rb

This adds a new feature to the `merge()` function such that it builds a
hash from hashes returned from a lambda when the function is given an
`Iterable` as its only argument.
This adds a 4.x version of merge that is backwards compatible (except it
generates different error messages for argument errors). Since a 4.x
version wins over a 3x the new version will win over the old except for
users that use the old API for calling functions (as expected; this is
fine).

(MODULES-8760) Add iterative feature to merge() function

---

README.md
lib/puppet/functions/stdlib/ip_in_range.rb
spec/functions/ip_in_range_spec.rb

It's very useful function from https://github.com/deanwilson/puppet-ip_in_range . Why you haven't include it so far?

Add a stdlib::ip_in_range() function

---

lib/puppet/parser/functions/range.rb

It is trivially easy to accidentally DOS a puppet master by requesting
a range larger than was intended, for example
`range('host00/index.html', 'host25/index.html')`. Because jruby's
implementation of unrolling the range is parallelized, this sort of
thing takes down the whole box.
The solution here is a simple sanity-check on it; we could get fancier
with a new argument specifying a larger size etc. if someone thinks it
needed.

Limit the maximum array size produced by range().

---

lib/puppet/parser/functions/fqdn_rand_string.rb

```
stdlib/lib/puppet/parser/functions/fqdn_rand_string.rb:21: syntax error, unexpected null
fqdn_rand_string(10, 'ABCDEF!@#$%^')
^
```

fix lib/puppet/parser/functions/fqdn_rand_string.rb:21: syntax error

---

README.md
spec/type_aliases/objectstore_gsuri_spec.rb
spec/type_aliases/objectstore_s3uri_spec.rb
spec/type_aliases/objectstore_spec.rb
types/objectstore.pp
types/objectstore/gsuri.pp
types/objectstore/s3uri.pp

Closes https://tickets.puppetlabs.com/browse/MODULES-9915
Add a type alias for Cloud Object Store URIs, e.g., (s3://mybucket/myfile).
These URIs are commonly used as sources for files, packages, etc. in Puppet modules. Some organizations even keep all sources in a specific cloud object store like s3 in order to limit downloads from the internet when applying a Puppet catalogue across potentially thousands of nodes.
It would be useful to have a type alias for these URIs.

(MODULES-9915) Add type aliases for cloud object store uris

---

lib/facter/pe_version.rb

It would be nice if PE stabilized on what it will support, but this works for the moment.

Fix PE detection (for the moment)

---

lib/puppet/functions/to_json_pretty.rb
spec/functions/to_json_pretty_spec.rb

This PR exposes all of the settings available in Ruby `JSON.pretty_generate`: https://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html#method-i-generate
Example:
```puppet
to_json_pretty(['one', 'two', nil, 'three'], true, {'indent' => '@@@@'})
```

Add support for additional options to to_json_pretty

---

spec/functions/to_json_pretty_spec.rb

Add two pending tests for `to_json_pretty` with parameter `skip_undef` enabled; current implementation only elides `nil` values from the top level.

Add pending tests for to_json_pretty with skip_undef enabled

---

lib/puppet/parser/functions/intersection.rb

Makes the exception message a bit more helpful.

intersection: show types in exception due to invalid arguments

---

lib/puppet/functions/stdlib/end_with.rb
spec/functions/end_with_spec.rb

This PR wraps the ruby `String.end_with?` function and exposes it to the
puppet DSL.

stdlib::end_with: create String.end_with function

---

lib/puppet/functions/start_with.rb
lib/puppet/functions/stdlib/end_with.rb
spec/functions/end_with_spec.rb
spec/functions/startswith_spec.rb

This is helpful in places where you need to use variables in the string
which needs to be compare e.g. something like this:
```puppet
$test.start_with("part${string}01")
```

Add start_with function

---

REFERENCE.md
lib/puppet/parser/functions/str2saltedpbkdf2.rb
spec/functions/str2saltedpbkdf2_spec.rb

This is designed to aid in setting passwords for OS x / macOS 10.8+
Pinging @binford2k and @DavidS since they helped me figure out what to do here.

Adding str2saltedpbkdf2 function

---

lib/puppet/functions/stdlib/start_with.rb
spec/functions/startswith_spec.rb

This function was originally introduced in #1086 but never got a
decision about the correct namespace. This commit adds the stdlib::
namespace to the start_with function after a discussion I had with
Daneel on Slack about this. This will at least align the namespace with
the corresponding end_with function to not confuse people.
I'm not considering this a breaking change because the function was never released.

Add correct namespace for start_with function

---

lib/facter/facter_dot_d.rb
lib/puppet/functions/to_json_pretty.rb

Call ::JSON to ensure it references the JSON library
from Ruby’s standard library instead of a random JSON namespace
that might be in scope due to user code.
For example::
https://github.com/puppetlabs/pdk/blob/master/lib/pdk/config/json.rb

(MODULES-10623) explicitly top-scope calls to JSON methods

---

lib/puppet/functions/to_json_pretty.rb

Ruby’s is written with UTF-8 characters, while all the other code is plain ASCII.

Fix UTF-8 to_json_pretty.rb entry

---

lib/puppet/parser/functions/defined_with_params.rb
spec/functions/defined_with_params_spec.rb

This fixes an issue where trying to match against any declared defined
type with a specific parameter would never return that there was a match
in the catalog.
This is relevant when trying to ensure that you don't have port
conflicts in services that can declare multiple instances of a service
through a given defined type, such as Apache.
This, previously valid call to the function now works as expected:
``defined_with_params(My::DefinedType, { 'port' => 1337 })``
MODULES-10729 #close

[MODULES-10729] defined_with_params - unnamed type

---

lib/puppet/parser/functions/defined_with_params.rb
spec/functions/defined_with_params_spec.rb

An edge case was missed previously where calling the
defined_with_params() function from inside a defined type on another
instance of the same defined type would always return a match because it
would match against itself.
This updates the code to ignore itself and also adds a debug line output
for any resource that was matched.
MODULES-10781 #close

[MODULES-10781] Fix defined type defined_with_params()

---

lib/facter/facter_dot_d.rb

For Puppet 7 we are dropping the `win32/dir` dependency as we only used constants from it, which we replaced with environment variables (see: https://github.com/puppetlabs/puppet/pull/8314).
This would become breaking when using the stdlib module with Puppet 7, as the win32 dependencies are no longer provided in the puppet gem.
Replace the usage of the `Dir::COMMON_APPDATA` with the `ALLUSERSPROFILE` environment variable.

(PUP-10653) Remove win32/dir constant usage

---

spec/type_aliases/datasize_spec.rb
types/datasize.pp

Many class/define parameters take a value representing a data size.
e.g. 1024Mb, 1024G, 100k
This new type provides a way to validate most common data type inputs

Stdlib::Datasize: This CR adds a new data size type alias

---

types/ensure/file.pp
types/ensure/file/directory.pp
types/ensure/file/file.pp
types/ensure/file/link.pp

This PR adds some new types
Stdlib::Ensure::File covers all file ensures
Stdlib::Ensure::File::Link covers only link and absent
Stdlib::Ensure::File::File covers only file and absent
Stdlib::Ensure::File::Directory covers only directory and absent

Add new types for Stdlib::Ensure::File

---

lib/puppet/functions/parsehocon.rb
spec/functions/parsehocon_spec.rb

This function aligns with the existing parsejson and parseyaml functions, providing similar functionality for HOCON strings. This is useful for dealing with Puppet configuration files, many of which are HOCON format.

Add parsehocon() function

---

spec/type_aliases/port__dynamic_spec.rb
spec/type_aliases/port__user_spec.rb
types/port/dynamic.pp
types/port/ephemeral.pp
types/port/registered.pp
types/port/user.pp

The IANA port registry and rfc6335 specify the following port ranges
* the System Ports, also known as the Well Known Ports, from 0-1023 (assigned by IANA)
* the User Ports, also known as the Registered Ports, from 1024-49151 (assigned by IANA)
* the Dynamic Ports, also known as the Private or Ephemeral Ports, from 49152-65535 (never assigned)
This PR adds the following types to capture this:
- `Stdlib::Port::User`
- `Stdlib::Port::Registered (alias to Stdlib::Port::User)`
- `Stdlib::Port::Dynamic`
- `Stdlib::Port::Ephemeral (alias to Stdlib::Port::Dynamic)`
We could drop the aliases and just pick on name to use or use both i dont have a strong prefrence; however my gut feeling is that most uses of the current Stdlib::Port::Unprivileged type would be better served by this newer …

Add additional types Stdlib::Port::Dynamic,Ephemeral,Registered,User}

---

CHANGELOG.md

There is a dupe 6.4.0 entry.  The first one is in fact the 6.5.0 release.

Fix latest release version in CHANGELOG.md

---

lib/puppet/functions/stdlib/end_with.rb
lib/puppet/functions/stdlib/start_with.rb
spec/functions/end_with_spec.rb
spec/functions/startswith_spec.rb

When using this library function on strings that come from a parameter,
they might be empty sometimes, rendering it difficult to use, having to
force hacks like.
"_${source}".stdlib::start_with('_puppet:///modules/')
Where `_` is added to make sure that the string is never empty.
In Ruby the `start_with?` function allows being used on empty strings,
and it returns `false` for any assertion to be done:
p ''.start_with?('test')
false
Also in Python the `startswith()` method returns `false` for empty
strings:
In [1]: print(''.startswith('test'))
False
As this logic seems the most extended and allows for a wider use of the
library, removing these corner cases when the string is empty seems like a good idea.

Allow start/end checks on empty strings

---

lib/puppet/functions/to_yaml.rb
spec/functions/to_yaml_spec.rb

This makes it possible to inject formatting options into the to_yaml function.

Allow options injection for to_yaml

---

.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/weekly.yml
CHANGELOG.md
CONTRIBUTING.md
HISTORY.md
README.md
REFERENCE.md
RELEASE_PROCESS.markdown
lib/facter/puppet_settings.rb
lib/puppet/parser/functions/is_absolute_path.rb
lib/puppet/parser/functions/pry.rb
lib/puppet/parser/functions/pw_hash.rb
readmes/README_ja_JP.md

Removal of any offensive or inappropriate terminology from the code base.

(IAC-1012) - Removal of Inappropriate Terminology

---

functions/ensure.pp
spec/functions/stdlib_ensure_spec.rb

This PR adds a new function to cast the ensureable property to a resource
specific value. e.g.
* `stdlib::ensure('present', 'service') == 'running'`
* `stdlib::ensure('present', 'directory') == 'directory'`
This is useful when you want to pass ensure to a custom class and
ensure all the resource get the correct value e.g.
```puppet
class foo(
Enum['present', 'absent'] $ensure = 'present'
) {
file {'/some/dir':
ensure => stdlib::ensure($ensure, 'directory')
}
file {'/some/file':
ensure => stdlib::ensure($ensure, 'file')
}
file {'/some/link':
ensure => stdlib::ensure($ensure, 'link')
}
service {'some-service':
ensure => stdlib::ensure($ensure, 'service')
}
}
```
something similar to this was discussed in #869

stdlib::ensure: new fuction to cast ensure values

---

spec/functions/load_module_metadata_spec.rb
spec/functions/loadjson_spec.rb
spec/functions/shell_escape_spec.rb
spec/functions/shell_join_spec.rb

This PR is made up of two commits:
Prior to this commit, the `spec/functions/shell_join_spec.rb` tests
were failing on Ruby 2.7 as the `Shellwords.shelljoin` method in
2.7 does not escape the `+` character.
Rather than have specific datasets for Ruby versions `< 2.7` and
`>= 2.7`, it seemed easiest to simply remove this character from
the tests.
In the context of Puppet 7 there are two subsequent calls to
File.read from the catalog generated from the tests of `loadjson_spec.rb`
and `load_module_metadata_spec.rb`
Prior to this commit, these calls were causing exceptions from
RSpec as the mock expectations for File.read were being thrown off.
This did not manifest on Puppet 5 or 6.
After this commit, any calls to File.read that do not conform to
the expected arguments we want to mock a …

(IAC-1228) Fix multiple spec test issues in Ruby 2.7

---

lib/puppet/parser/functions/range.rb

Prior to this commit, on Ruby 2.7, the range() method would NOT
throw an ArgumentError exception if it was passed an invalid value as the
step size (3rd arg). Instead, it would return an array of size
1,000,000 with repeated integer values of the 2nd arg.
The function invokes Ruby's in built range method and `step` to
define a step size to increment / decrement by  and then passes the
output to `first`, limiting to the first 1,000,000 values.
On Ruby < 2.7, `step` would throw an `ArgumentError` if the step
size passed was `0`:
```
1..2).step(0).first(1_000_000).to_a
Traceback (most recent call last):
5: from ~/.rvm/rubies/ruby-2.5.8/bin/irb:11:in `<main>'
4: from (irb):7
3: from (irb):7:in `first'
2: from (irb):7:in `each'
1: from (irb):7:in `step'
ArgumentError (step can't be 0)
``` …

(IAC-1414) Throw error in range() function when step size invalid

---

spec/type_aliases/email_spec.rb
types/email.pp

Add new type to validate emails.  The regex has been taken from the
[html5 spec][1]
[1]: https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address

Stdlib::Email type

---

spec/type_aliases/email_spec.rb
types/email.pp

Setting stricter email validation. Currently this type allows for new lines. 
This fix is in relation to the following comment: https://github.com/puppetlabs/puppetlabs-stdlib/pull/1160#issuecomment-776633336
Thank you for bringing this to our attention @pegasd 👍

(bugfix) Setting stricter email validation

---

.github/workflows/auto_release.yml
.sync.yml
.travis.yml
metadata.json
provision.yaml

Remove Puppet 5 from testing and bump minimal version to 6.0.0
pdk version: `1.18.1`

pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0

---

lib/puppet/parser/functions/pw_hash.rb
spec/functions/pw_hash_spec.rb

pw_hash: add support for bcrypt variants

---

lib/puppet/functions/merge.rb
spec/functions/merge_spec.rb

`Hash` defaults to `Hash[Scalar,Data]` however, class/type references are valid hash values but are not covered by the `Data` type.
see also https://github.com/voxpupuli/puppet-jenkins/pull/909

(MODULES-11099) Make merge parameter data types actually backwards compatible

---

lib/puppet/parser/functions/ensure_packages.rb
spec/functions/ensure_packages_spec.rb

Flip `installed` and `present` in Function `ensure_packages`.
Puppet-Type `package` defaults to `installed` and not to `present` (compare [here](https://github.com/puppetlabs/puppet/blob/main/lib/puppet/type/package.rb#L148) ).
This Misconception lies in the Code since the most early Days.
With flipping these two Values, Rspec-Tests do not have to be adapted, when migrating from `package {}` to `ensure_packages()`.

Fix ensure_packages

---

lib/puppet/functions/to_python.rb
lib/puppet/functions/to_ruby.rb
spec/functions/to_python_spec.rb
spec/functions/to_ruby_spec.rb

Add two new utility functions to transform Puppet data structures into their corresponding representation in Python and Ruby.
These functions are aimed to help writing templates of Ruby / Python code when managing configuration files in these languages with Puppet.  Quoting strings, managing `undef` can be a bit tedious:
```
EMAIL_USE_TLS = <%= String($taiga::back::email_use_tls, '%T') %>
EMAIL_HOST = <%= if $taiga::back::email_host { String($taiga::back::email_host, '%p') } else { 'None' } %>
```
These functions make this more readable:
```
EMAIL_USE_TLS = <%= $taiga::back::email_use_tls.to_python %>
EMAIL_HOST = <%= $taiga::back::email_host.to_python %>
```
This initial work took place in https://github.com/voxpupuli/puppet-python/pull/616 but it was suggested to move the code in …

New function to_python() / to_ruby()

---

lib/puppet/functions/os_version_gte.rb
spec/functions/os_version_gte_spec.rb

os_version_gte: fix version comparison logic

---

lib/puppet/functions/to_toml.rb
lib/puppet_x/stdlib.rb
lib/puppet_x/stdlib/toml_dumper.rb
spec/functions/to_toml_spec.rb

This adds a function to stdlib for converting Puppet hashes to TOML. This is useful for Go services like Telegraf and Gitlab CI Runner than use TOML as their config format. Having this as a common function alleviates the problem of trying to load the `toml-rb` gem before running catalogs (chicken before the egg problem).

Added to_toml function

---

lib/puppet/parser/functions/uriescape.rb
spec/functions/uriescape_spec.rb

URI.escape was deprecated in ruby-2.7 and removed in ruby-3.x. This
change is breaking stdlib. This is described in detail here [1].
Replacing URI.escape with URI::DEFAULT_PARSER is working properly.
This is affecting openstack-tripleo [2]
[1] https://bugs.ruby-lang.org/issues/17309
[2] https://bugs.launchpad.net/tripleo/+bug/1937166

(MODULES-11126) Replacing URI.escape with URI::DEFAULT_PARSER

---

functions/ensure.pp
spec/functions/stdlib_ensure_spec.rb

This only adds 'installed' and 'absent' support, not 'latest'.

stdlib::ensure: Add support for package resource

---

REFERENCE.md
lib/puppet/functions/to_json.rb
lib/puppet/functions/to_yaml.rb
spec/functions/to_yaml_spec.rb

Use Ruby 2.5's `transform_keys` method to symbolize the keys in the
`options` parameter before passing to Ruby's `to_yaml` function.
Note, this requires Puppet 6 and above for the required Ruby version to
be available on both the agent (for `puppet apply`) _and_ the server
(Puppetserver 6 ships with JRuby 9.2.x which is Ruby 2.5 compatible).
Also fixed up the docs of the `to_json` function for better consistency
between the two functions.

Fix `to_yaml` `options` parameter

---

lib/puppet/parser/functions/batch_escape.rb
lib/puppet/parser/functions/powershell_escape.rb
spec/functions/batch_escape_spec.rb
spec/functions/powershell_escape_spec.rb

The `shell_escape` function is not usable on windows where batch files and
powershell scripts use different escape rules.
Add two functions to escape strings on windots for batch (`batch_escape`)
and powershell (`powershell_escape`).

(MODULES-4976) Add windows escaping functions

---

lib/puppet/parser/functions/str2saltedpbkdf2.rb

The documentation in str2saltedpbkdf2.rb did not have the right length salt. 
OS X versions 10.15 and higher require the salt to be 32-bytes. Since Puppet's user  resource requires the value to be hex encoded, the length of the salt's string must be 64. str2saltedpbkdf2.rb was updated to reflect this.

(maint) Update str2saltedpbkdf2.rb to use the correct salt length

---

lib/puppet/parser/functions/load_module_metadata.rb

Just a simple capitalisation error on usage

Update load_module_metadata.rb to correct capitalisation in strings documentartion

---

lib/puppet/functions/to_python.rb
lib/puppet/functions/to_ruby.rb
spec/functions/to_python_spec.rb
spec/functions/to_ruby_spec.rb

`:undef` was used in old Puppet functions, but modern Puppet 4 functions receive `undef` Puppet values as `nil` Ruby values.  This cause to_python() to serialize `undef` as `nil` instead of `None`, which is not valid Python code.
Fix the to_python() behavior by comparing with `nil`.  Update the test suite accordingly.
While here, also adjust the to_ruby() function which had the same wrong logic but was not causing trouble because in Ruby, we want to serialize `nil` to `nil` :-)

Fix serialization of undef in to_python()

---

README.md
lib/puppet/functions/stdlib/str2resource.rb
manifests/init.pp
manifests/manage.pp
spec/classes/manage_spec.rb
spec/functions/str2resource_spec.rb

I'll need a bit of help loading the resources into the catalog for the tests, but in theory that should be all that is required.

MODULES-11309 : convert a string to a resource

---

lib/puppet/provider/file_line/ruby.rb
spec/acceptance/file_line_spec.rb

In noop mode, file_line should not fail if the file does not exist.
MODULES-2892 #close

(MODULES-2892) Handle missing file in file_line

---

REFERENCE.md
lib/puppet/functions/ensure_packages.rb
lib/puppet/parser/functions/ensure_packages.rb
spec/functions/ensure_packages_spec.rb

As a first step before fixing https://github.com/puppetlabs/puppetlabs-stdlib/pull/1196 in a separate PR, this PR converts to the new API and gets rid of some code duplication etc. in the process.

Convert `ensure_packages` to new API and refactor

---

README.md
manifests/manage.pp
spec/classes/manage_spec.rb

This should make the resources much less sensitive to parse order,
since pupppet is already "doing the right thing" to Strings in this
parameter location.

Simplify stdlib::manage

---

lib/puppet/parser/functions/parsejson.rb
spec/functions/parsejson_spec.rb

The use of PSON is deprecated and mostly removed from Puppet.
Switch this function from using PSON to a real JSON parsing
library via the MultiJson helper in Puppet::Util::Json.

Switch parsejson() from PSON to JSON parsing

---

REFERENCE.md
lib/puppet/functions/parsepson.rb
spec/functions/parsepson_spec.rb

This commit adds a new function to parse PSON formatted JSON.
This functionality was formally covered by `parsejson` which, despite its name, defaulted to PSON.
However this has been changed so that the function now accurately uses JSON, with this function covering the potential need for PSON too specifically be used.

(FEAT) Add function parsepson

---

metadata.json

Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
In this commit:
Support for AIX 5.3 and 6.1 was removed.
Support for Windows 7, 8.1 and 10 was removed.
Support for Windows Server 2008 and 2008 R2 was removed. ﻿
The list of supported OSs can be found here:
https://puppet.com/docs/pe/2021.7/supported_operating_systems.html

(MAINT) Drop support for AIX + Windows EOL OSs

---

lib/puppet_x/stdlib/toml_dumper.rb

Prior to this PR using stdlib/to_toml function in a separate environment outside of production will result in the following error if the latest version doesn't also live in production:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Internal Server Error: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- puppet_x/stdlib
```
This PR fixes the issue by updating code to use the correct paths for require_relative.

(CONT-200) Fix require relative paths

---

lib/facter/root_home.rb
spec/unit/facter/root_home_spec.rb

Prior to this PR, this module contained instances of Facter::Util::Resolution.exec and Facter::Util::Resolution.which, which are deprecated. This PR aims to replace these exec helpers with their supported Facter::Core::Execution counterparts.
This PR:
Replaces all Facter::Util::Resolution instances with corresponding Facter::Core::Execution exec helpers

(CONT-173) - Updating deprecated facter instances

---

lib/facter/package_provider.rb

The metadata states it's only compatible with Puppet 6+ so maintaining compatibility is useless and can only slow things down.

Drop Puppet < 3.6 support in package_provider fact

---

lib/facter/root_home.rb
spec/unit/facter/root_home_spec.rb

This uses Ruby's Etc library to determine the root home. This avoids shelling out and writing multiple implementations.

Determine root_home without shelling out

---

lib/puppet/parser/functions/pw_hash.rb
spec/functions/pw_hash_spec.rb

This corrects the regex used by the pw_hash function for bcrypt-type hashes. The first two characters are interpreted as a strength parameter by bcrypt, and must take a value between 4 and 31 inclusive.

Correct bcrypt salt regex

---

functions/ensure.pp
spec/functions/stdlib_ensure_spec.rb

Often custom resources only support present/absent for the ensure parameter and often the inclusion of theses resources are enabled via some boolean value as such i often find my self using the following pattern
```puppet
$ensure_feature = $enable_feature.bool2str('ensure', 'present')
```
This patch updates the stdlib::ensure function so we can simplify this to
```puppet
$ensure_feature = $enable_feature.stdlib::ensure   # or ...
$ensure_feature = stdlib::ensure($enable_feature) 
```

stdlib::ensure: update function to support the generic case

---

REFERENCE.md
lib/puppet/functions/stdlib/crc32.rb
spec/functions/crc32_spec.rb

CRC32 is a handy way to run trivial checks against values.  Unlike the SHA hashing series generating collisions is fairly trivial which makes it useful for describing secret data in a public manner.  For example, "Is you app using secret `18fbd270` or `7d5469f0`" cannot possibly be used to reconstruct the secret but does permit concrete conversation about the secret itself.  This can be further useful when the developers do not have direct access to the secret in question.
It is also handy for establishing an application specific shared seed across multiple hosts, for establishing trivial user sharding, or other applications where uniqueness is not actually an asset.

Add `stdlib::crc32`

---

REFERENCE.md
lib/puppet/functions/stdlib/sha256.rb
spec/functions/sha256_spec.rb

This exposes the `sha256` function for computation against random data.

Add `stdlib::sha256`

---

spec/type_aliases/ensure_package_spec.rb
types/ensure/package.pp

Like the ones for file, service.
Valid values taken from https://puppet.com/docs/puppet/7/types/package.html#package-attribute-ensure

Add Stdlib::Ensure::Package type

---

lib/facter/root_home.rb

In 657cd7126e6d01f883c2e038dae449aea30db5d0 it was assumed that Etc would never be available on Windows and that the LoadError would catch it. Turns out that was an invalid assumption. This uses the safe operator to gracefully handle it.
Fixes #1293

Safely handle a missing root user

---

spec/functions/fqdn_rand_string_spec.rb

Since Puppet `7.23.0` `fqdn_rand` uses the modern structured `networking` fact instead of the legacy `fqdn` fact.
In this commit we mock the new fact if using `7.23.0` or later.
Rebase of https://github.com/puppetlabs/puppetlabs-stdlib/pull/1294 incorporating @joshcooper 's suggestion.

(PUP-11752) Fix fqdn_rand_string_spec.rb test

---

lib/puppet/functions/ensure_packages.rb
spec/functions/ensure_packages_spec.rb

This unbreaks the breaking change made in #1196
Also refactored to create a separate dispatch method for the case when `packages` is a `Hash`, and having that call the main `ensure_packages` method. This simplifies the code by only ever calling `ensure_resource` instead of calling `ensure_resources` for hashes.
Defaulting `default_attributes` to an empty hash instead of `nil` in the method signatures further simplifies the code.
Fixes #1252

Make ensure_packages work with `ensure => present`

---

REFERENCE.md
lib/puppet/functions/has_interface_with.rb
lib/puppet/functions/stdlib/has_interface_with.rb
spec/functions/has_interface_with_spec.rb

Convert the function to the modern function API as a namespaced function and use the `networking` fact instead of legacy facts.
A non-namespaced shim is also created (but marked deprecated), to preserve compatibility.

Modernise `has_interface_with` function

---

types/ip/address/cidr.pp

This type was the only one missing from the hierarchy.

Add Stdlib::IP::Address::CIDR

---

lib/puppet/functions/validate_domain_name.rb
spec/functions/validate_domain_name_spec.rb

In #1345, the `validate_domain_name()` function was rewritten to the
Puppet 4.x syntax, but the behavior was slightly changed since we
previously did not allow passing no parameter at all.
Add code to assert as least one parameter is passed to restore the
previous behavior and raise an error when called without parameter.

Fix validate_domain_name called without parameters

---

functions/deferrable_epp.pp

If none of the input variables are `Deferred`, then `deferrable_epp` returns the result of calling normal `epp`.
The `epp` function however will return a `Sensitive` if any of the variables it was called with were `Sensitive`.
See https://github.com/puppetlabs/puppet/pull/8330
Adding `Sensitive[String]` to the list of allowed return types fixes this.

Allow `deferrable_epp` to return a `Sensitive[String]`

---

lib/puppet/functions/validate_legacy.rb
spec/functions/validate_legacy_spec.rb

This is a follow-up to #1352 and in particular https://github.com/puppetlabs/puppetlabs-stdlib/pull/1352#issuecomment-1538844946.
I reproduce the content bellow so that we can discuss this, and provide an implementation.
`validate_legacy()` was used with a data type and a validation function. If the value was matched by both the data type and the validation function, it produced no warning, otherwise it produced a warning if the new data type was matched but the legacy validation function was not accepting the value or an deprecation message if the data type was not matched but the legacy validation was accepted.  The validation functions used are the ones being removed by this PR, so `validate_legacy()` needs to be taken care of.
The table bellow summarize the current behavior of …

Deprecate the `validate_legacy()` function

---

lib/puppet/parser/functions/load_module_metadata.rb
lib/puppet/parser/functions/loadjson.rb
lib/puppet/parser/functions/loadyaml.rb
spec/functions/load_module_metadata_spec.rb
spec/functions/loadjson_spec.rb
spec/functions/loadyaml_spec.rb

In 7999ff2aebbd2d85a231318f1e466b36d6dab84e the cops were disabled, but Ruby 3.2 has removed the method.
Fixes #1354

Remove deprecated File.exists?

---

lib/puppet/parser/functions/loadyaml.rb
spec/functions/loadyaml_spec.rb

Ruby 3.1 includes Psych 4.0 which no longer loads aliases by default. Since aliases are part of the yaml spec, it seems sensible to re-add support.

re-add support for loading aliases in yaml files

---

lib/puppet/functions/stdlib/fqdn_rand_string.rb
spec/functions/fqdn_rand_string_spec.rb

The function use to be able to accept `undef` as its second argument.
eg.
```puppet
fqdn_rand_string(10, undef, 'custom seed')
```
Using `undef` to mean 'use the default' is much more conventional than `''` (empty string).
This commit restores the old interface broken in `9.0.0`

Fix `fqdn_rand_string` regression

---

lib/puppet/parser/functions/pw_hash.rb

The method as it is currently is causing issues with certain customers crypto setups

(CONT-1035) Alter logic of pw_hash

---

lib/puppet/functions/deprecation.rb
spec/functions/deprecation_spec.rb

In this change, an optional third parameter is added to the `deprecation` function.  The default behaviour remains the same, but when the third parameter is set to `false`, Puppet's `strict` setting is ignored. This means that even if `strict` is set to `error`, no exception will be raised when this function is called, and a warning will be logged instead.
This is a prerequisite for #1373

Add `use_strict_setting` parameter to `deprecation` function

---

Rakefile
lib/puppet/functions/batch_escape.rb
lib/puppet/functions/ensure_packages.rb
lib/puppet/functions/fqdn_rand_string.rb
lib/puppet/functions/has_interface_with.rb
lib/puppet/functions/merge.rb
lib/puppet/functions/os_version_gte.rb
lib/puppet/functions/parsehocon.rb
lib/puppet/functions/powershell_escape.rb
lib/puppet/functions/seeded_rand.rb
lib/puppet/functions/seeded_rand_string.rb
lib/puppet/functions/shell_escape.rb
lib/puppet/functions/to_json.rb
lib/puppet/functions/to_json_pretty.rb
lib/puppet/functions/to_python.rb
lib/puppet/functions/to_ruby.rb
lib/puppet/functions/to_toml.rb
lib/puppet/functions/to_yaml.rb
lib/puppet/functions/type_of.rb
lib/puppet/functions/validate_domain_name.rb
lib/puppet/functions/validate_email_address.rb

Previously, when a user had the Puppet setting `strict` set to `error` (which is the default in Puppet 8), a call to one of stdlib's functions via the deprecated non-namespaced function would cause a hard failure instead of just logging a warning and calling the real namespaced function.
In this change, all of our shims have been updated to call `deprecation` with its new third parameter, (`use_strict_setting`), set to `false`. The non-namespaced versions will now only ever log warnings informing users to moved to the namespaced versions. It will not raise exceptions even if `strict` is set to `error`.
This change will make it much easier for users to migrate to stdlib 9 (and to upgrade modules that now depend on stdlib 9)
Fixes #1373
(Note, this PR description was updated after the …

Ignore Puppet's `strict` setting when calling function without namespace

---

lib/puppet/functions/merge.rb

The block parameter functionality of the deprecated top-level merge was broken when it was moved to the stdlib namespace in #1356.  This restores the original behavior.

Re-add block support to deprecated top-level merge

---

.rubocop_todo.yml

Fixing rubocop failure
Add any additional context about the problem here. 
Mention any related issues or pull requests.

Fixing rubocop failure

---

REFERENCE.md
types/host.pp

While Puppet doesn't appear to care about IP vs Ip, but Kafo does and can't find the correct type. This aligns the usage with the actual name in the file.
Fixes: fcbd4267fd83 ("Remove deprecated Stdlib::Compat::* data types")

Correct casing of Stdlib::IP::Address

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
README.md

- The internal scanning tool requires to explicitly declare about dependent licenses for the given module.
- CI is failing with docker provisioner due to filesystem mount issue.
Update README.md with declaring license details.

CAT-945 - Update README.md LICENSE

---

lib/puppet/functions/stdlib/sort_by.rb
spec/functions/sort_by_spec.rb

Add new Ruby function `stdlib::sort_by()`, emulating native Ruby's `Enumerable.sort_by()` for Puppet.
`stdlib::sort_by()` supports sorting Strings, Arrays and Hashes
- Arrays, since that is the most prominent use-case
- Strings, because it is a subset of Iterable, even though I cannot imagine any sensible proc besides `clone`/`copy`, which would be identical to basic `String::sort()`
- Hashes, because that was found to be missing in #1376, even though there likely is little demand for it
#1376

Add function stdlib::sort_by

---

lib/puppet/parser/functions/pw_hash.rb

See linked issue. `pw_hash` with `bcrypt` does not work on puppet master because of https://github.com/puppetlabs/puppetlabs-stdlib/commit/8d525d24a510d377b29a2aed2654ed2de854b94f
`bcrypt` is not supported by the java implementation.
Add any additional context about the problem here. 
- Only JRuby setup (e.g. puppet server with puppet agents) are affected. Local `puppet apply` not affected.
#1389 - Issue for the bug
https://github.com/puppetlabs/puppetlabs-stdlib/pull/1370 - Bug introduced

(#1389) - pw_hash with bcrypt not working on puppet master

---

manifests/manage.pp
spec/classes/manage_spec.rb
templates/manage_spec.epp

This one only covers epp templates.
Users want to make use of stdlib::manage also with templates.
As hiera can not evaluate functions, we must implement this as Puppet code.

Allow usage of file templates with stdlib::manage

---

.fixtures.yml
metadata.json

Removes fixtures puppet_agent pinned ref, should never be needed.

Support for Amazon linux 2 and 2023

---

.github/workflows/labeller.yml

Reverts puppetlabs/puppetlabs-stdlib#1429
the labeler needs this event and uses it safely

Revert "pdksync - (ITHELP-87329) - replace pull_request_target with pull_request"
