README.markdown, lib/puppet/parser/functions/prefix.rb, spec/functions/prefix_spec.rb
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
Closes #275
=> Add support for hashes in the prefix function

README.markdown
Using a ####, github will create a link. This makes it so I can link
someone directly to the function I want to show them.
=> Make each function a link in the readme

lib/puppet/type/file_line.rb
=> Clarifying behaviour of attributes and adding an extra example.

README.markdown
During technical review, please also take notice to the following related tickets that are being addressed during this update:
DOCUMENT-261 
DOCUMENT-305
=> DOC-1504: Readme edits

lib/puppet/parser/functions/is_mac_address.rb
let the computer do the counting and repetition and case
=> simplify mac address regex

README.markdown, lib/puppet/parser/functions/validate_slength.rb, spec/functions/validate_slength_spec.rb
=> Add validate_slength's optional 3rd arg to README

README.markdown, lib/puppet/parser/functions/validate_integer.rb
Removed use of "crap" from documentation because I'm a buzzkill.
=> Remove colorful language from module.

CHANGELOG.md, metadata.json, spec/acceptance/ensure_resource_spec.rb, spec/spec_helper_acceptance.rb
Diff: https://github.com/puppetlabs/puppetlabs-stdlib/compare/4.7.0...4.8.x
=> Prep 4.8.0

lib/facter/service_provider.rb
This is to improve speed on Facter resolution of service_provider fact
that was just introduced in PR #506 .  The improvements go from 280ms
resolution time approx. down to 2ms resolution time approx. by adding
require statements.
=> fixup-PR#506 Speed improvements in facter resolution

README.markdown, lib/puppet/type/file_line.rb
This mostly needed extraction of the existing doc strings from
the type.
=> (MODULES-2421) improve description of file_line

lib/facter/pe_version.rb, spec/unit/facter/pe_version_spec.rb
Add a quick check to ensure puppetversion value is not nil and supporting test.
=> Add check to ensure regex does not throw for none type.

README.markdown
Just some edits to new or changed material.
=> edits to README

lib/puppet/parser/functions/str2bool.rb
=> Fix str2bool error message

README.markdown
=> Fix markdown indentation

README.markdown
This adds a in-depth explanation of the process to migrate to Puppet 4
data types.
=> Update documentation for validate_legacy

README.markdown
Mostly validate_legacy stuff, although I cleaned up the deprecate function text a bit too.
=> MODULES-3774: stdlib validate_legacy review

lib/puppet/parser/functions/getparam.rb, spec/functions/getparam_spec.rb
This is the idiomatic version of #634, and also addresses
the test failures.
Original-Fix-By: Michiel Brandenburg <michiel@silverstreet.com>
=> (MODULES-3933) Fix getparam for 'false' values

CHANGELOG.md, Gemfile, README.markdown, metadata.json
* Changelog & Thanks
* Add known issues/version compatiblity to README
* Whitespace fixes
* Update version and dependency information
* Fix issue tracker URL
=> Release prep for 4.13.0

types/compat/bool.pp
This corrects puppet-linting error.
=> Remove leading spaces

README.markdown
Updates to clarify (I hope) deprecation language and note which functions are deprecated.
=> MODULES-4008: clarify deprecation language

lib/puppet/functions/deprecation.rb, spec/acceptance/deprecation_spec.rb
Reverts puppetlabs/puppetlabs-stdlib#685
=> Revert "Call site output for deprecation warnings"

.travis.yml, Gemfile
https://github.com/puppetlabs/modulesync_configs/pull/102
=> (MODULES-3631) msync Gemfile for 1.9 frozen strings

README.markdown
Updated documentation for this function to be consistent with
the function itself.
=> Change - Update str2bool documentation

README.markdown, lib/puppet/functions/type_of.rb
First merge accidentally squashed and merged.
=> Release mergeback - second attempt

spec/functions/any2array_spec.rb, spec/functions/ensure_resource_spec.rb
WIP - Tests for internationalization. Sending out for feedback before I continue to write tests for all of the stdlib functions.  I plan on writing only unit tests as I am only testing that the function is compatible and can handle UTF8 characters etc.
This PR covers 2 functions:
1) ensure_resource
2) any2array
=> (FM-6019) - i18N tests for Spike

spec/functions/concat_spec.rb, spec/functions/count_spec.rb, spec/functions/delete_at_spec.rb, spec/functions/delete_spec.rb, spec/functions/delete_values_spec.rb
Tests to cover i18n tests for the following functions: 
- concat
- count 
- delete 
- delete_at
- delete_values
Grouping in multiple PRs for traceability.
=> Modules 4429 unit tests

spec/functions/concat_spec.rb, spec/functions/defined_with_params_spec.rb, spec/functions/dig44_spec.rb, spec/functions/dos2unix_spec.rb, spec/functions/ensure_packages_spec.rb, spec/functions/getparam_spec.rb, spec/functions/is_mac_address_spec.rb, spec/functions/keys_spec.rb, spec/functions/load_module_metadata_spec.rb, spec/functions/loadjson_spec.rb, spec/functions/loadyaml_spec.rb, spec/functions/parsejson_spec.rb, spec/functions/parseyaml_spec.rb, spec/functions/range_spec.rb, spec/functions/seeded_rand_spec.rb, spec/functions/squeeze_spec.rb
Unit tests for i18n support. This PR includes unit tests for the following functions:
- concat_spec.rb
- defined_with_params_spec.rb
- dig44_spec.rb
- dos2unix_spec.rb
- ensure_packages_spec.rb
- getparam_spec.rb
- is_mac_address_spec.rb
- keys_spec.rb
- load_module_metadata_spec.rb
- loadjson_spec.rb
- loadyaml_spec.rb
- parsejson_spec.rb
- parseyaml_spec.rb
- range_spec.rb
- seeded_rand_spec.rb
- squeeze_spec.rb
=> (FM-6063) - Unit tests for high effort functions

spec/aliases/absolute_path_spec.rb, spec/aliases/httpsurl_spec.rb, spec/aliases/httpurl_spec.rb, spec/aliases/unixpath_spec.rb, spec/aliases/windowspath_spec.rb
Unit tests to ensure i18N compatibility for Data Types in stdlib.
This PR includes the following Data Types:
- absolute_path_spec
- httpsurl_spec
- httpurl_spec
- unixpath_spec
- windowspath_spec
=> (FM-6085) - Unit tests for Data Types

spec/unit/puppet/type/file_line_spec.rb
This PR includes tests to ensure that file_line supports UTF8 and Double Byte Characters.
=> (FM-6086) - Unit tests for Resource Types

locales/puppetlabs-stdlib.pot
This is adding a POT file for the module.
=> (FM-6116) - Adding POT file for metadata.json

lib/puppet/provider/file_line/ruby.rb
=> Ruby 1.8 doesn't support open_args

lib/puppet/parser/functions/defined_with_params.rb, spec/functions/defined_with_params_spec.rb
=> (PE-20308) Correct boundary for 4.5 vs 4.6

README.markdown
One ToC, two code samples fixed.
=> (MODULES-4706) prerelease fixes

metadata.json
MODULES-4821 puppetlabs-stdlib: Update the version compatibility to >= 4.7.0 < 5.0.0
=> MODULES-4821 puppetlabs-stdlib: Update the version compatibility to >= 4.7.0 < 5.0.0

CHANGELOG.md, metadata.json
This isn't actually another release, we decided to do 4.18.0 instead of 4.17.2
=> (MODULES-5436) release prep for 4.18.0

README.md
I rebased release on to master, so changes in master to the readme were not interpretted as changes on release in the payload sent to transifex. This commit should mark the README as modified in Transifex and hopefully they will be able to see the changes, e.g. to_json, to_yaml docs.
=> (maint) re-send push action to transifex

CHANGELOG.md
=> Pre release

spec/functions/min_spec.rb
Thanks for fixing it quickly! Just adding a test :-)
=> Add test for https://github.com/puppetlabs/puppetlabs-stdlib/pull/850

README.md
fixed typos, formatting issues
=> (maint) fixed typos, formatting issues

README.md
Updates to the README to avoid conflicts during translation process.
=> (LOC-124) - Update readme to avoid translation conflicts

readmes/README_ja_JP.md
Manually checking this file in since triggering it from TX did not work.
=> (MODULES-6951) Updating translations for readmes/README_ja_JP.md

lib/puppet/parser/functions/dirname.rb, spec/functions/dirname_spec.rb
creating a clean PR as i messed up https://github.com/puppetlabs/puppetlabs-stdlib/pull/913
=> (maint) - Cause dirname to fail when passed undef

README.md
This commit made minor grammar and style edits to the README.
=> (stdlib) Minor edits to README

.gitignore, .pdkignore, .rubocop.yml, .sync.yml, .travis.yml, Gemfile, Rakefile, appveyor.yml, metadata.json, spec/default_facts.yml, spec/spec_helper.rb
(FM-7392) - Puppet 6 Testing Changes
pdk version: `1.7.0`
=> pdksync - (FM-7392) - Puppet 6 Testing Changes

spec/functions/deprecation_spec.rb, spec/functions/join_keys_to_values_spec.rb, spec/functions/pick_default_spec.rb, spec/functions/size_spec.rb
https://tickets.puppetlabs.com/browse/MODULES-8219
=> (MODULES-8219) - Fix to unit test's to account for Puppet 5.5.7

README.md
This commit contains minor edits.
=> (MODULES-8992) Docs review

lib/puppet/parser/functions/abs.rb
Will need an update in REFERENCE.md too.
=> Fix typo in abs function

REFERENCE.md, lib/puppet/parser/functions/grep.rb, readmes/README_ja_JP.md
fixes "invalid multibyte char (US-ASCII) error"
=> replace non-ascii "—" char by "-"

spec/unit/facter/pe_version_spec.rb
Facter.collection is no longer available in Facter 4
=> (maint) remove unsupported API collection

CHANGELOG.md, REFERENCE.md, lib/puppet/functions/stdlib/end_with.rb, lib/puppet/functions/stdlib/start_with.rb, metadata.json
Request for a review.
1.Generated changelog
2.Generated References.
3.Modify the function examples to show in correct format
4.Acceptance tests running clean on github actions and travis
5.Unit tests running clean on travis(in github action its failing-ruby version is different in github 2.6.3 on travis 2.5.7)
=> (IAC-579) Release prep v6.3.0

lib/puppet/parser/functions/seeded_rand.rb
Ref: https://github.com/puppetlabs/puppet/commit/3dcf66bb547
cc @kjetilho
=> seeded_rand: update funtion to ensure it returns an int not String

metadata.json
(feat) - Bump Puppet boundary
pdk version: `1.18.1`
=> (feat) Add support for Puppet 7

.github/workflows/nightly.yml, .github/workflows/pr_test.yml, .rubocop.yml, .travis.yml, Rakefile, appveyor.yml, metadata.json
(MAINT) PDK update for GHA workflows + Litmus updates
pdk version: `1.18.1`
=> pdksync - (MAINT) PDK update for GHA workflows + Litmus updates

.github/workflows/auto_release.yml, Gemfile, Rakefile, metadata.json
PDK Update for auto release prep workflow
pdk version: `1.18.1`
=> pdksync - PDK Update for auto release prep workflow

REFERENCE.md, lib/puppet/functions/stdlib/xml_encode.rb, spec/functions/xml_encode_spec.rb
Example for unit test taken from
https://stackoverflow.com/questions/1443816/convert-an-arbitrary-string-to-xml-in-ruby
=> Add `xml_encode` function

REFERENCE.md
Regenerate references with the following fix
https://github.com/puppetlabs/puppet-strings/pull/303
=> REFERENCE.md: apply fix for unique anchors from puppet strings
